defmodule RsolvWeb.EmailsHTML do
  @moduledoc """
  Module for rendering email templates using Phoenix 1.7's compiled HEEx approach.

  Templates are compiled at build time from .heex files in templates/email/.
  This provides better performance and compile-time validation compared to
  runtime file reading.

  ## Template Functions

  This module provides two types of functions for each email template:

  - Template functions (e.g., `payment_failed/1`) - Generated by `embed_templates`,
    these render the HEEx template with the provided assigns
  - Render functions (e.g., `render_payment_failed/1`) - Apply default assigns
    and convert the rendered template to a binary string for email delivery

  ## Usage

      # In email composition
      html_body = EmailsHTML.render_payment_failed(%{
        customer_name: "Jane",
        amount_due: "$19.99",
        invoice_id: "inv_123"
      })
  """
  use RsolvWeb, :html

  # Embed all email templates from the priv/templates/email directory
  # This generates functions like payment_failed/1, welcome/1, etc.
  # The path is relative to the application root
  embed_templates "../../../priv/templates/email/*"

  # List of all email templates for which we generate render_* functions
  @email_templates [
    :early_access_guide,
    :early_access_welcome,
    :feature_deep_dive,
    :feedback_request,
    :first_issue,
    :getting_started,
    :payment_failed,
    :setup_verification,
    :success_checkin,
    :welcome
  ]

  @doc """
  Applies default assigns to ensure required template variables are present.

  ## Default Assigns

  - `:app_url` - "https://rsolv.dev"
  - `:docs_url` - "https://rsolv.dev/docs"
  - `:billing_url` - "https://rsolv.dev/billing"
  - `:unsubscribe_url` - "https://rsolv.dev/unsubscribe?email={email}"
  - `:first_name` - "there" (friendly fallback)
  - `:customer_name` - "there" (friendly fallback, same as first_name)
  - `:email` - "" (empty string fallback)
  - `:amount_due` - "$0.00"
  - `:invoice_id` - ""
  - `:attempt_count` - 0
  - `:credit_balance` - 0
  - `:next_payment_attempt_text` - nil
  - `:usage_stats` - %{}

  Existing assigns are not overwritten.
  """
  def with_defaults(assigns) do
    assigns
    |> Map.new()
    |> Map.put_new(:app_url, "https://rsolv.dev")
    |> Map.put_new(:docs_url, "https://rsolv.dev/docs")
    |> Map.put_new(:billing_url, "https://rsolv.dev/billing")
    |> Map.put_new_lazy(:unsubscribe_url, fn ->
      "https://rsolv.dev/unsubscribe?email=#{assigns[:email]}"
    end)
    |> Map.put_new(:first_name, "there")
    |> Map.put_new(:customer_name, "there")
    |> Map.put_new(:email, "")
    |> Map.put_new(:amount_due, "$0.00")
    |> Map.put_new(:invoice_id, "")
    |> Map.put_new(:attempt_count, 0)
    |> Map.put_new(:credit_balance, 0)
    |> Map.put_new(:next_payment_attempt_text, nil)
    |> Map.put_new(:usage_stats, %{})
  end

  # Generate render_* functions for all email templates using a macro
  # This eliminates boilerplate while maintaining clarity
  for template <- @email_templates do
    @doc """
    Renders the #{template} email template with default assigns applied.

    Returns the rendered HTML as a binary string suitable for email delivery.
    """
    def unquote(:"render_#{template}")(assigns) do
      assigns
      |> with_defaults()
      |> unquote(template)()
      |> Phoenix.HTML.Safe.to_iodata()
      |> IO.iodata_to_binary()
    end
  end
end
