# Security Patterns Database Seed
# Generated: 2025-06-08T03:50:51.450Z
# Total Patterns: 78 (actual patterns from TypeScript files)
#
# Note: The marketing claim of 448 patterns appears to be inflated.
# This seed contains the 143 actual patterns found in the codebase.

alias RsolvApi.Repo
alias RsolvApi.Security.{SecurityPattern, PatternTier}
import Ecto.Query

IO.puts("🔍 Loading security patterns...")

# Clear existing patterns
Repo.delete_all(SecurityPattern)

# Get tier IDs
tiers = Repo.all(PatternTier) |> Enum.map(&{&1.name, &1.id}) |> Enum.into(%{})

# Pattern distribution:
# Total: 78 patterns
# By tier:
#   public: 9 patterns
#   protected: 67 patterns
#   ai: 2 patterns
# By language:
#   python: 19 patterns
#   ruby: 19 patterns
#   java: 17 patterns
#   elixir: 12 patterns
#   javascript: 10 patterns
#   typescript: 1 patterns

patterns_data = [
  %{
    name: "SQL Injection via String Concatenation",
    description: "Detects SQL injection vulnerabilities from string concatenation",
    language: "javascript",
    type: "sql_injection",
    severity: "high",
    cwe_id: "CWE-89",
    owasp_category: "A03:2021 - Injection",
    remediation: "Use parameterized queries or prepared statements",
    confidence: "medium",
    framework: nil,
    regex_patterns: [],
    safe_usage_patterns: [],
    example_code: nil,
    fix_template: nil,
    tier_id: Map.get(tiers, "public"),
    is_active: true,
    source: "rsolv",
    tags: ["javascript", "severity-high", "owasp-A03"],
    inserted_at: {:placeholder, :timestamp},
    updated_at: {:placeholder, :timestamp}
  },
  %{
    name: "XSS via innerHTML Assignment",
    description: "Detects XSS vulnerabilities from innerHTML assignments",
    language: "javascript",
    type: "xss",
    severity: "high",
    cwe_id: "CWE-79",
    owasp_category: "A03:2021 - Injection",
    remediation: "Use textContent or sanitize input before setting innerHTML",
    confidence: "medium",
    framework: nil,
    regex_patterns: [],
    safe_usage_patterns: [],
    example_code: nil,
    fix_template: nil,
    tier_id: Map.get(tiers, "public"),
    is_active: true,
    source: "rsolv",
    tags: ["javascript", "severity-high", "owasp-A03"],
    inserted_at: {:placeholder, :timestamp},
    updated_at: {:placeholder, :timestamp}
  },
  %{
    name: "XSS via document.write",
    description: "Detects XSS vulnerabilities from document.write calls",
    language: "javascript",
    type: "xss",
    severity: "high",
    cwe_id: "CWE-79",
    owasp_category: "A03:2021 - Injection",
    remediation: "Avoid document.write and use safe DOM manipulation methods",
    confidence: "medium",
    framework: nil,
    regex_patterns: [],
    safe_usage_patterns: [],
    example_code: nil,
    fix_template: nil,
    tier_id: Map.get(tiers, "public"),
    is_active: true,
    source: "rsolv",
    tags: ["javascript", "severity-high", "owasp-A03"],
    inserted_at: {:placeholder, :timestamp},
    updated_at: {:placeholder, :timestamp}
  },
  %{
    name: "React Router Unvalidated Redirect",
    description: "Detects unvalidated redirects in React Router",
    language: "javascript",
    type: "open_redirect",
    severity: "medium",
    cwe_id: "CWE-601",
    owasp_category: "A01:2021 - Broken Access Control",
    remediation: "Validate redirect URLs against a whitelist before navigation",
    confidence: "medium",
    framework: nil,
    regex_patterns: [],
    safe_usage_patterns: [],
    example_code: nil,
    fix_template: nil,
    tier_id: Map.get(tiers, "protected"),
    is_active: true,
    source: "rsolv",
    tags: ["javascript", "severity-medium", "owasp-A01"],
    inserted_at: {:placeholder, :timestamp},
    updated_at: {:placeholder, :timestamp}
  },
  %{
    name: "Node.js Path Traversal",
    description: "Detects path traversal vulnerabilities in file operations",
    language: "javascript",
    type: "path_traversal",
    severity: "high",
    cwe_id: "CWE-22",
    owasp_category: "A01:2021 - Broken Access Control",
    remediation: "Use path.join() and validate paths to prevent directory traversal",
    confidence: "medium",
    framework: nil,
    regex_patterns: [],
    safe_usage_patterns: [],
    example_code: nil,
    fix_template: nil,
    tier_id: Map.get(tiers, "public"),
    is_active: true,
    source: "rsolv",
    tags: ["javascript", "severity-high", "owasp-A01"],
    inserted_at: {:placeholder, :timestamp},
    updated_at: {:placeholder, :timestamp}
  },
  %{
    name: "Node.js Server-Side Request Forgery",
    description: "Detects SSRF vulnerabilities in HTTP requests",
    language: "javascript",
    type: "ssrf",
    severity: "medium",
    cwe_id: nil,
    owasp_category: nil,
    remediation: "Review and fix the security issue",
    confidence: "medium",
    framework: nil,
    regex_patterns: [],
    safe_usage_patterns: [],
    example_code: nil,
    fix_template: nil,
    tier_id: Map.get(tiers, "protected"),
    is_active: true,
    source: "rsolv",
    tags: ["javascript", "severity-medium"],
    inserted_at: {:placeholder, :timestamp},
    updated_at: {:placeholder, :timestamp}
  },
  %{
    name: "TypeScript Non-Null Assertion",
    description: "Detects unsafe non-null assertions that may cause runtime errors",
    language: "typescript",
    type: "null_pointer_dereference",
    severity: "medium",
    cwe_id: "CWE-476",
    owasp_category: "A04:2021 - Insecure Design",
    remediation: "Use proper null checks instead of non-null assertions",
    confidence: "medium",
    framework: nil,
    regex_patterns: ["\\w+!\\.(?!length|toString|valueOf)"],
    safe_usage_patterns: [],
    example_code: nil,
    fix_template: nil,
    tier_id: Map.get(tiers, "protected"),
    is_active: true,
    source: "rsolv",
    tags: ["typescript", "severity-medium", "owasp-A04"],
    inserted_at: {:placeholder, :timestamp},
    updated_at: {:placeholder, :timestamp}
  },
  %{
    name: "Express Missing CSRF Protection",
    description: "Detects missing CSRF protection in Express applications",
    language: "javascript",
    type: "csrf",
    severity: "medium",
    cwe_id: "CWE-352",
    owasp_category: "A01:2021 - Broken Access Control",
    remediation: "Implement CSRF protection using csurf or similar middleware",
    confidence: "medium",
    framework: nil,
    regex_patterns: [],
    safe_usage_patterns: [],
    example_code: nil,
    fix_template: nil,
    tier_id: Map.get(tiers, "protected"),
    is_active: true,
    source: "rsolv",
    tags: ["javascript", "severity-medium", "owasp-A01"],
    inserted_at: {:placeholder, :timestamp},
    updated_at: {:placeholder, :timestamp}
  },
  %{
    name: "Express Missing Rate Limiting",
    description: "Detects missing rate limiting on sensitive endpoints",
    language: "javascript",
    type: "denial_of_service",
    severity: "medium",
    cwe_id: "CWE-770",
    owasp_category: "A04:2021 - Insecure Design",
    remediation: "Implement rate limiting on authentication endpoints",
    confidence: "medium",
    framework: nil,
    regex_patterns: [],
    safe_usage_patterns: [],
    example_code: nil,
    fix_template: nil,
    tier_id: Map.get(tiers, "protected"),
    is_active: true,
    source: "rsolv",
    tags: ["javascript", "severity-medium", "owasp-A04"],
    inserted_at: {:placeholder, :timestamp},
    updated_at: {:placeholder, :timestamp}
  },
  %{
    name: "WebSocket Missing Origin Validation",
    description: "Detects missing origin validation in WebSocket connections",
    language: "javascript",
    type: "improper_input_validation",
    severity: "medium",
    cwe_id: nil,
    owasp_category: nil,
    remediation: "Review and fix the security issue",
    confidence: "medium",
    framework: nil,
    regex_patterns: [],
    safe_usage_patterns: [],
    example_code: nil,
    fix_template: nil,
    tier_id: Map.get(tiers, "protected"),
    is_active: true,
    source: "rsolv",
    tags: ["javascript", "severity-medium"],
    inserted_at: {:placeholder, :timestamp},
    updated_at: {:placeholder, :timestamp}
  },
  %{
    name: "SSRF with DNS Rebinding",
    description: "Detects SSRF vulnerabilities susceptible to DNS rebinding",
    language: "javascript",
    type: "ssrf",
    severity: "medium",
    cwe_id: nil,
    owasp_category: nil,
    remediation: "Review and fix the security issue",
    confidence: "medium",
    framework: nil,
    regex_patterns: [],
    safe_usage_patterns: [],
    example_code: nil,
    fix_template: nil,
    tier_id: Map.get(tiers, "protected"),
    is_active: true,
    source: "rsolv",
    tags: ["javascript", "severity-medium"],
    inserted_at: {:placeholder, :timestamp},
    updated_at: {:placeholder, :timestamp}
  },
  %{
    name: "python-sql-injection-format",
    description: "",
    language: "python",
    type: "sql_injection",
    severity: "high",
    cwe_id: nil,
    owasp_category: nil,
    remediation: "Use parameterized queries with execute() method parameters",
    confidence: "medium",
    framework: nil,
    regex_patterns: [],
    safe_usage_patterns: [],
    example_code: nil,
    fix_template: nil,
    tier_id: Map.get(tiers, "protected"),
    is_active: true,
    source: "rsolv",
    tags: ["python", "severity-high"],
    inserted_at: {:placeholder, :timestamp},
    updated_at: {:placeholder, :timestamp}
  },
  %{
    name: "python-sql-injection-fstring",
    description: "",
    language: "python",
    type: "sql_injection",
    severity: "high",
    cwe_id: nil,
    owasp_category: nil,
    remediation: "Use parameterized queries instead of f-string formatting",
    confidence: "medium",
    framework: nil,
    regex_patterns: [],
    safe_usage_patterns: [],
    example_code: nil,
    fix_template: nil,
    tier_id: Map.get(tiers, "protected"),
    is_active: true,
    source: "rsolv",
    tags: ["python", "severity-high"],
    inserted_at: {:placeholder, :timestamp},
    updated_at: {:placeholder, :timestamp}
  },
  %{
    name: "python-sql-injection-concat",
    description: "",
    language: "python",
    type: "sql_injection",
    severity: "high",
    cwe_id: nil,
    owasp_category: nil,
    remediation: "Use parameterized queries with execute() method parameters",
    confidence: "medium",
    framework: nil,
    regex_patterns: [],
    safe_usage_patterns: [],
    example_code: nil,
    fix_template: nil,
    tier_id: Map.get(tiers, "public"),
    is_active: true,
    source: "rsolv",
    tags: ["python", "severity-high"],
    inserted_at: {:placeholder, :timestamp},
    updated_at: {:placeholder, :timestamp}
  },
  %{
    name: "python-command-injection-subprocess-shell",
    description: "",
    language: "python",
    type: "command_injection",
    severity: "high",
    cwe_id: nil,
    owasp_category: nil,
    remediation: "Use shell=False and pass command as list of arguments",
    confidence: "medium",
    framework: nil,
    regex_patterns: [],
    safe_usage_patterns: [],
    example_code: nil,
    fix_template: nil,
    tier_id: Map.get(tiers, "protected"),
    is_active: true,
    source: "rsolv",
    tags: ["python", "severity-high"],
    inserted_at: {:placeholder, :timestamp},
    updated_at: {:placeholder, :timestamp}
  },
  %{
    name: "python-unsafe-pickle",
    description: "",
    language: "python",
    type: "insecure_deserialization",
    severity: "critical",
    cwe_id: nil,
    owasp_category: nil,
    remediation: "Use json.loads() or implement custom deserialization with validation",
    confidence: "medium",
    framework: nil,
    regex_patterns: [],
    safe_usage_patterns: [],
    example_code: nil,
    fix_template: nil,
    tier_id: Map.get(tiers, "protected"),
    is_active: true,
    source: "rsolv",
    tags: ["python", "severity-critical"],
    inserted_at: {:placeholder, :timestamp},
    updated_at: {:placeholder, :timestamp}
  },
  %{
    name: "python-unsafe-eval",
    description: "",
    language: "python",
    type: "insecure_deserialization",
    severity: "critical",
    cwe_id: nil,
    owasp_category: nil,
    remediation: "Use ast.literal_eval() for safe evaluation of literals",
    confidence: "medium",
    framework: nil,
    regex_patterns: [],
    safe_usage_patterns: [],
    example_code: nil,
    fix_template: nil,
    tier_id: Map.get(tiers, "protected"),
    is_active: true,
    source: "rsolv",
    tags: ["python", "severity-critical"],
    inserted_at: {:placeholder, :timestamp},
    updated_at: {:placeholder, :timestamp}
  },
  %{
    name: "python-weak-hash-md5",
    description: "",
    language: "python",
    type: "weak_cryptography",
    severity: "medium",
    cwe_id: nil,
    owasp_category: nil,
    remediation: "Use SHA-256 or SHA-3 for cryptographic hashing",
    confidence: "medium",
    framework: nil,
    regex_patterns: [],
    safe_usage_patterns: [],
    example_code: nil,
    fix_template: nil,
    tier_id: Map.get(tiers, "protected"),
    is_active: true,
    source: "rsolv",
    tags: ["python", "severity-medium"],
    inserted_at: {:placeholder, :timestamp},
    updated_at: {:placeholder, :timestamp}
  },
  %{
    name: "python-weak-hash-sha1",
    description: "",
    language: "python",
    type: "weak_cryptography",
    severity: "medium",
    cwe_id: nil,
    owasp_category: nil,
    remediation: "Use SHA-256 or SHA-3 for cryptographic hashing",
    confidence: "medium",
    framework: nil,
    regex_patterns: [],
    safe_usage_patterns: [],
    example_code: nil,
    fix_template: nil,
    tier_id: Map.get(tiers, "protected"),
    is_active: true,
    source: "rsolv",
    tags: ["python", "severity-medium"],
    inserted_at: {:placeholder, :timestamp},
    updated_at: {:placeholder, :timestamp}
  },
  %{
    name: "python-debug-true",
    description: "",
    language: "python",
    type: "debug_mode",
    severity: "medium",
    cwe_id: nil,
    owasp_category: nil,
    remediation: "Set DEBUG = False in production environments",
    confidence: "medium",
    framework: nil,
    regex_patterns: [],
    safe_usage_patterns: [],
    example_code: nil,
    fix_template: nil,
    tier_id: Map.get(tiers, "public"),
    is_active: true,
    source: "rsolv",
    tags: ["python", "severity-medium"],
    inserted_at: {:placeholder, :timestamp},
    updated_at: {:placeholder, :timestamp}
  },
  %{
    name: "python-unsafe-yaml-load",
    description: "",
    language: "python",
    type: "insecure_deserialization",
    severity: "critical",
    cwe_id: nil,
    owasp_category: nil,
    remediation: "Use yaml.safe_load() or yaml.load() with SafeLoader",
    confidence: "medium",
    framework: nil,
    regex_patterns: [],
    safe_usage_patterns: [],
    example_code: nil,
    fix_template: nil,
    tier_id: Map.get(tiers, "protected"),
    is_active: true,
    source: "rsolv",
    tags: ["python", "severity-critical"],
    inserted_at: {:placeholder, :timestamp},
    updated_at: {:placeholder, :timestamp}
  },
  %{
    name: "Missing Authentication in Rails Controller",
    description: "Detects Rails controllers without authentication filters",
    language: "ruby",
    type: "broken_access_control",
    severity: "high",
    cwe_id: "CWE-862",
    owasp_category: "A01:2021 - Broken Access Control",
    remediation: "Add before_action :authenticate_user! to protect sensitive actions",
    confidence: "medium",
    framework: nil,
    regex_patterns: ["class\\s+\\w+Controller\\s*<\\s*ApplicationController(?:(?!before_action|before_filter|authenticate).)*end", "def\\s+(admin|delete|update|create)(?:(?!current_user|logged_in|authenticate).)*end"],
    safe_usage_patterns: [],
    example_code: nil,
    fix_template: nil,
    tier_id: Map.get(tiers, "protected"),
    is_active: true,
    source: "rsolv",
    tags: ["ruby", "severity-high", "owasp-A01"],
    inserted_at: {:placeholder, :timestamp},
    updated_at: {:placeholder, :timestamp}
  },
  %{
    name: "Mass Assignment Vulnerability",
    description: "Detects unfiltered params in model operations",
    language: "ruby",
    type: "mass_assignment",
    severity: "high",
    cwe_id: "CWE-915",
    owasp_category: "A01:2021 - Broken Access Control",
    remediation: "Use strong parameters: params.require(:user).permit(:name, :email)",
    confidence: "medium",
    framework: nil,
    regex_patterns: ["\\.(create|update|update_attributes|assign_attributes)\\s*\\(\\s*params(?!\\s*\\.\\s*(require|permit))", "User\\.new\\s*\\(\\s*params\\["],
    safe_usage_patterns: [],
    example_code: nil,
    fix_template: nil,
    tier_id: Map.get(tiers, "protected"),
    is_active: true,
    source: "rsolv",
    tags: ["ruby", "severity-high", "owasp-A01"],
    inserted_at: {:placeholder, :timestamp},
    updated_at: {:placeholder, :timestamp}
  },
  %{
    name: "Weak Cryptography - MD5",
    description: "MD5 is cryptographically broken and should not be used",
    language: "ruby",
    type: "weak_cryptography",
    severity: "medium",
    cwe_id: "CWE-327",
    owasp_category: "A02:2021 - Cryptographic Failures",
    remediation: "Use SHA-256 or SHA-3: Digest::SHA256.hexdigest(data)",
    confidence: "medium",
    framework: nil,
    regex_patterns: ["Digest::MD5", "OpenSSL::Digest::MD5", "\\.md5\\("],
    safe_usage_patterns: [],
    example_code: nil,
    fix_template: nil,
    tier_id: Map.get(tiers, "public"),
    is_active: true,
    source: "rsolv",
    tags: ["ruby", "severity-medium", "owasp-A02"],
    inserted_at: {:placeholder, :timestamp},
    updated_at: {:placeholder, :timestamp}
  },
  %{
    name: "Weak Random Number Generation",
    description: "Using predictable random number generation",
    language: "ruby",
    type: "weak_cryptography",
    severity: "medium",
    cwe_id: "CWE-330",
    owasp_category: "A04:2021 - Insecure Design",
    remediation: "Use SecureRandom for security-sensitive randomness",
    confidence: "medium",
    framework: nil,
    regex_patterns: ["\\brand\\s*\\(", "Random\\.rand(?!\\s*\\(\\s*SecureRandom)", "\\bsrand\\s*\\("],
    safe_usage_patterns: [],
    example_code: nil,
    fix_template: nil,
    tier_id: Map.get(tiers, "protected"),
    is_active: true,
    source: "rsolv",
    tags: ["ruby", "severity-medium", "owasp-A04"],
    inserted_at: {:placeholder, :timestamp},
    updated_at: {:placeholder, :timestamp}
  },
  %{
    name: "Debug Mode Enabled",
    description: "Debug mode exposes sensitive information",
    language: "ruby",
    type: "debug_mode",
    severity: "medium",
    cwe_id: "CWE-489",
    owasp_category: "A05:2021 - Security Misconfiguration",
    remediation: "Remove debug statements and disable debug mode in production",
    confidence: "medium",
    framework: nil,
    regex_patterns: ["config\\.consider_all_requests_local\\s*=\\s*true", "\\bbyebug\\b", "\\bdebugger\\b", "binding\\.pry"],
    safe_usage_patterns: [],
    example_code: nil,
    fix_template: nil,
    tier_id: Map.get(tiers, "protected"),
    is_active: true,
    source: "rsolv",
    tags: ["ruby", "severity-medium", "owasp-A05"],
    inserted_at: {:placeholder, :timestamp},
    updated_at: {:placeholder, :timestamp}
  },
  %{
    name: "Use of eval()",
    description: "eval() can execute arbitrary code",
    language: "ruby",
    type: "vulnerable_components",
    severity: "high",
    cwe_id: "CWE-95",
    owasp_category: "A06:2021 - Vulnerable and Outdated Components",
    remediation: "Avoid eval() or validate/sanitize input thoroughly",
    confidence: "medium",
    framework: nil,
    regex_patterns: ["\\beval\\s*\\(", "instance_eval", "class_eval", "module_eval"],
    safe_usage_patterns: [],
    example_code: nil,
    fix_template: nil,
    tier_id: Map.get(tiers, "protected"),
    is_active: true,
    source: "rsolv",
    tags: ["ruby", "severity-high", "owasp-A06"],
    inserted_at: {:placeholder, :timestamp},
    updated_at: {:placeholder, :timestamp}
  },
  %{
    name: "Weak Password Storage",
    description: "Passwords stored without proper hashing",
    language: "ruby",
    type: "broken_authentication",
    severity: "critical",
    cwe_id: "CWE-256",
    owasp_category: "A07:2021 - Identification and Authentication Failures",
    remediation: "Use BCrypt for password hashing",
    confidence: "medium",
    framework: nil,
    regex_patterns: ["password\\s*=\\s*Digest::(MD5|SHA1)", "user\\.password\\s*=\\s*params", "password.*?\\.downcase(?!.*bcrypt)"],
    safe_usage_patterns: [],
    example_code: nil,
    fix_template: nil,
    tier_id: Map.get(tiers, "protected"),
    is_active: true,
    source: "rsolv",
    tags: ["ruby", "severity-critical", "owasp-A07"],
    inserted_at: {:placeholder, :timestamp},
    updated_at: {:placeholder, :timestamp}
  },
  %{
    name: "Unsafe Deserialization with Marshal",
    description: "Marshal.load can execute arbitrary code",
    language: "ruby",
    type: "insecure_deserialization",
    severity: "critical",
    cwe_id: "CWE-502",
    owasp_category: "A08:2021 - Software and Data Integrity Failures",
    remediation: "Use JSON or MessagePack for serialization",
    confidence: "medium",
    framework: nil,
    regex_patterns: ["Marshal\\.load", "Marshal\\.restore"],
    safe_usage_patterns: [],
    example_code: nil,
    fix_template: nil,
    tier_id: Map.get(tiers, "protected"),
    is_active: true,
    source: "rsolv",
    tags: ["ruby", "severity-critical", "owasp-A08"],
    inserted_at: {:placeholder, :timestamp},
    updated_at: {:placeholder, :timestamp}
  },
  %{
    name: "Unsafe YAML Loading",
    description: "YAML.load can execute arbitrary code",
    language: "ruby",
    type: "insecure_deserialization",
    severity: "high",
    cwe_id: "CWE-502",
    owasp_category: "A08:2021 - Software and Data Integrity Failures",
    remediation: "Use YAML.safe_load for untrusted input",
    confidence: "medium",
    framework: nil,
    regex_patterns: ["YAML\\.load(?!_file|_stream)", "Psych\\.load(?!_file|_stream)"],
    safe_usage_patterns: [],
    example_code: nil,
    fix_template: nil,
    tier_id: Map.get(tiers, "protected"),
    is_active: true,
    source: "rsolv",
    tags: ["ruby", "severity-high", "owasp-A08"],
    inserted_at: {:placeholder, :timestamp},
    updated_at: {:placeholder, :timestamp}
  },
  %{
    name: "SSRF via open-uri",
    description: "Unvalidated URLs in open() can lead to SSRF",
    language: "ruby",
    type: "open_redirect",
    severity: "high",
    cwe_id: "CWE-918",
    owasp_category: "A10:2021 - Server-Side Request Forgery",
    remediation: "Validate URLs against allowlist before making requests",
    confidence: "medium",
    framework: nil,
    regex_patterns: ["open\\s*\\(\\s*params", "URI\\.open\\s*\\(\\s*params", "Net::HTTP\\.get.*params"],
    safe_usage_patterns: [],
    example_code: nil,
    fix_template: nil,
    tier_id: Map.get(tiers, "protected"),
    is_active: true,
    source: "rsolv",
    tags: ["ruby", "severity-high", "owasp-A10"],
    inserted_at: {:placeholder, :timestamp},
    updated_at: {:placeholder, :timestamp}
  },
  %{
    name: "XSS in ERB Templates",
    description: "Using raw() or html_safe without sanitization",
    language: "ruby",
    type: "xss",
    severity: "medium",
    cwe_id: "CWE-79",
    owasp_category: "A03:2021 - Injection",
    remediation: "Use Rails sanitize helpers or escape output by default",
    confidence: "medium",
    framework: nil,
    regex_patterns: ["<%=\\s*raw\\s+", "\\.html_safe(?!.*sanitize)", "<%==\\s*\\w+"],
    safe_usage_patterns: [],
    example_code: nil,
    fix_template: nil,
    tier_id: Map.get(tiers, "protected"),
    is_active: true,
    source: "rsolv",
    tags: ["ruby", "severity-medium", "owasp-A03"],
    inserted_at: {:placeholder, :timestamp},
    updated_at: {:placeholder, :timestamp}
  },
  %{
    name: "Open Redirect",
    description: "Unvalidated redirects can lead to phishing",
    language: "ruby",
    type: "open_redirect",
    severity: "medium",
    cwe_id: "CWE-601",
    owasp_category: "A01:2021 - Broken Access Control",
    remediation: "Validate redirect URLs against an allowlist",
    confidence: "medium",
    framework: nil,
    regex_patterns: ["redirect_to\\s+params", "redirect_to\\s+request\\.(referrer|referer)"],
    safe_usage_patterns: [],
    example_code: nil,
    fix_template: nil,
    tier_id: Map.get(tiers, "protected"),
    is_active: true,
    source: "rsolv",
    tags: ["ruby", "severity-medium", "owasp-A01"],
    inserted_at: {:placeholder, :timestamp},
    updated_at: {:placeholder, :timestamp}
  },
  %{
    name: "java-sql-injection-statement",
    description: "",
    language: "java",
    type: "sql_injection",
    severity: "high",
    cwe_id: nil,
    owasp_category: nil,
    remediation: "Use PreparedStatement with parameterized queries",
    confidence: "medium",
    framework: nil,
    regex_patterns: [],
    safe_usage_patterns: [],
    example_code: nil,
    fix_template: nil,
    tier_id: Map.get(tiers, "protected"),
    is_active: true,
    source: "rsolv",
    tags: ["java", "severity-high"],
    inserted_at: {:placeholder, :timestamp},
    updated_at: {:placeholder, :timestamp}
  },
  %{
    name: "java-sql-injection-string-format",
    description: "",
    language: "java",
    type: "sql_injection",
    severity: "high",
    cwe_id: nil,
    owasp_category: nil,
    remediation: "Use PreparedStatement with setString(), setInt(), etc.",
    confidence: "medium",
    framework: nil,
    regex_patterns: [],
    safe_usage_patterns: [],
    example_code: nil,
    fix_template: nil,
    tier_id: Map.get(tiers, "protected"),
    is_active: true,
    source: "rsolv",
    tags: ["java", "severity-high"],
    inserted_at: {:placeholder, :timestamp},
    updated_at: {:placeholder, :timestamp}
  },
  %{
    name: "java-unsafe-deserialization",
    description: "",
    language: "java",
    type: "insecure_deserialization",
    severity: "critical",
    cwe_id: nil,
    owasp_category: nil,
    remediation: "Implement custom readObject() with validation or use safe serialization libraries",
    confidence: "medium",
    framework: nil,
    regex_patterns: [],
    safe_usage_patterns: [],
    example_code: nil,
    fix_template: nil,
    tier_id: Map.get(tiers, "protected"),
    is_active: true,
    source: "rsolv",
    tags: ["java", "severity-critical"],
    inserted_at: {:placeholder, :timestamp},
    updated_at: {:placeholder, :timestamp}
  },
  %{
    name: "java-xpath-injection",
    description: "",
    language: "java",
    type: "xpath_injection",
    severity: "high",
    cwe_id: nil,
    owasp_category: nil,
    remediation: "Use parameterized XPath expressions or validate input",
    confidence: "medium",
    framework: nil,
    regex_patterns: [],
    safe_usage_patterns: [],
    example_code: nil,
    fix_template: nil,
    tier_id: Map.get(tiers, "protected"),
    is_active: true,
    source: "rsolv",
    tags: ["java", "severity-high"],
    inserted_at: {:placeholder, :timestamp},
    updated_at: {:placeholder, :timestamp}
  },
  %{
    name: "java-command-injection-runtime-exec",
    description: "",
    language: "java",
    type: "command_injection",
    severity: "critical",
    cwe_id: nil,
    owasp_category: nil,
    remediation: "Use ProcessBuilder with array of arguments and validate input",
    confidence: "medium",
    framework: nil,
    regex_patterns: [],
    safe_usage_patterns: [],
    example_code: nil,
    fix_template: nil,
    tier_id: Map.get(tiers, "protected"),
    is_active: true,
    source: "rsolv",
    tags: ["java", "severity-critical"],
    inserted_at: {:placeholder, :timestamp},
    updated_at: {:placeholder, :timestamp}
  },
  %{
    name: "java-command-injection-processbuilder",
    description: "",
    language: "java",
    type: "command_injection",
    severity: "high",
    cwe_id: nil,
    owasp_category: nil,
    remediation: "Use ProcessBuilder with separate arguments and validate input",
    confidence: "medium",
    framework: nil,
    regex_patterns: [],
    safe_usage_patterns: [],
    example_code: nil,
    fix_template: nil,
    tier_id: Map.get(tiers, "protected"),
    is_active: true,
    source: "rsolv",
    tags: ["java", "severity-high"],
    inserted_at: {:placeholder, :timestamp},
    updated_at: {:placeholder, :timestamp}
  },
  %{
    name: "java-path-traversal-file",
    description: "",
    language: "java",
    type: "path_traversal",
    severity: "medium",
    cwe_id: nil,
    owasp_category: nil,
    remediation: "Validate and sanitize file paths, use Paths.get() with validation",
    confidence: "medium",
    framework: nil,
    regex_patterns: [],
    safe_usage_patterns: [],
    example_code: nil,
    fix_template: nil,
    tier_id: Map.get(tiers, "protected"),
    is_active: true,
    source: "rsolv",
    tags: ["java", "severity-medium"],
    inserted_at: {:placeholder, :timestamp},
    updated_at: {:placeholder, :timestamp}
  },
  %{
    name: "java-path-traversal-fileinputstream",
    description: "",
    language: "java",
    type: "path_traversal",
    severity: "medium",
    cwe_id: nil,
    owasp_category: nil,
    remediation: "Validate file paths and use Files.newInputStream() with proper validation",
    confidence: "medium",
    framework: nil,
    regex_patterns: [],
    safe_usage_patterns: [],
    example_code: nil,
    fix_template: nil,
    tier_id: Map.get(tiers, "protected"),
    is_active: true,
    source: "rsolv",
    tags: ["java", "severity-medium"],
    inserted_at: {:placeholder, :timestamp},
    updated_at: {:placeholder, :timestamp}
  },
  %{
    name: "java-weak-hash-md5",
    description: "",
    language: "java",
    type: "weak_cryptography",
    severity: "medium",
    cwe_id: nil,
    owasp_category: nil,
    remediation: "Use SHA-256 or SHA-3 for cryptographic hashing",
    confidence: "medium",
    framework: nil,
    regex_patterns: [],
    safe_usage_patterns: [],
    example_code: nil,
    fix_template: nil,
    tier_id: Map.get(tiers, "protected"),
    is_active: true,
    source: "rsolv",
    tags: ["java", "severity-medium"],
    inserted_at: {:placeholder, :timestamp},
    updated_at: {:placeholder, :timestamp}
  },
  %{
    name: "java-weak-hash-sha1",
    description: "",
    language: "java",
    type: "weak_cryptography",
    severity: "medium",
    cwe_id: nil,
    owasp_category: nil,
    remediation: "Use SHA-256 or SHA-3 for cryptographic hashing",
    confidence: "medium",
    framework: nil,
    regex_patterns: [],
    safe_usage_patterns: [],
    example_code: nil,
    fix_template: nil,
    tier_id: Map.get(tiers, "protected"),
    is_active: true,
    source: "rsolv",
    tags: ["java", "severity-medium"],
    inserted_at: {:placeholder, :timestamp},
    updated_at: {:placeholder, :timestamp}
  },
  %{
    name: "java-weak-cipher-des",
    description: "",
    language: "java",
    type: "weak_cryptography",
    severity: "high",
    cwe_id: nil,
    owasp_category: nil,
    remediation: "Use AES with appropriate key sizes (AES-256)",
    confidence: "medium",
    framework: nil,
    regex_patterns: [],
    safe_usage_patterns: [],
    example_code: nil,
    fix_template: nil,
    tier_id: Map.get(tiers, "protected"),
    is_active: true,
    source: "rsolv",
    tags: ["java", "severity-high"],
    inserted_at: {:placeholder, :timestamp},
    updated_at: {:placeholder, :timestamp}
  },
  %{
    name: "java-xxe-documentbuilder",
    description: "",
    language: "java",
    type: "xxe",
    severity: "high",
    cwe_id: nil,
    owasp_category: nil,
    remediation: "Enable secure processing and disable external entity processing",
    confidence: "medium",
    framework: nil,
    regex_patterns: [],
    safe_usage_patterns: [],
    example_code: nil,
    fix_template: nil,
    tier_id: Map.get(tiers, "protected"),
    is_active: true,
    source: "rsolv",
    tags: ["java", "severity-high"],
    inserted_at: {:placeholder, :timestamp},
    updated_at: {:placeholder, :timestamp}
  },
  %{
    name: "java-xxe-saxparser",
    description: "",
    language: "java",
    type: "xxe",
    severity: "high",
    cwe_id: nil,
    owasp_category: nil,
    remediation: "Enable secure processing and disable external entity processing",
    confidence: "medium",
    framework: nil,
    regex_patterns: [],
    safe_usage_patterns: [],
    example_code: nil,
    fix_template: nil,
    tier_id: Map.get(tiers, "protected"),
    is_active: true,
    source: "rsolv",
    tags: ["java", "severity-high"],
    inserted_at: {:placeholder, :timestamp},
    updated_at: {:placeholder, :timestamp}
  },
  %{
    name: "java-ldap-injection",
    description: "",
    language: "java",
    type: "ldap_injection",
    severity: "high",
    cwe_id: nil,
    owasp_category: nil,
    remediation: "Use parameterized LDAP queries and validate input",
    confidence: "medium",
    framework: nil,
    regex_patterns: [],
    safe_usage_patterns: [],
    example_code: nil,
    fix_template: nil,
    tier_id: Map.get(tiers, "protected"),
    is_active: true,
    source: "rsolv",
    tags: ["java", "severity-high"],
    inserted_at: {:placeholder, :timestamp},
    updated_at: {:placeholder, :timestamp}
  },
  %{
    name: "java-hardcoded-password",
    description: "",
    language: "java",
    type: "hardcoded_secret",
    severity: "high",
    cwe_id: nil,
    owasp_category: nil,
    remediation: "Use environment variables or secure configuration management",
    confidence: "medium",
    framework: nil,
    regex_patterns: [],
    safe_usage_patterns: [],
    example_code: nil,
    fix_template: nil,
    tier_id: Map.get(tiers, "public"),
    is_active: true,
    source: "rsolv",
    tags: ["java", "severity-high"],
    inserted_at: {:placeholder, :timestamp},
    updated_at: {:placeholder, :timestamp}
  },
  %{
    name: "java-weak-random",
    description: "",
    language: "java",
    type: "weak_cryptography",
    severity: "medium",
    cwe_id: nil,
    owasp_category: nil,
    remediation: "Use SecureRandom for security-sensitive random values",
    confidence: "medium",
    framework: nil,
    regex_patterns: [],
    safe_usage_patterns: [],
    example_code: nil,
    fix_template: nil,
    tier_id: Map.get(tiers, "protected"),
    is_active: true,
    source: "rsolv",
    tags: ["java", "severity-medium"],
    inserted_at: {:placeholder, :timestamp},
    updated_at: {:placeholder, :timestamp}
  },
  %{
    name: "Unsafe Ecto Fragment Usage",
    description: "Detects potentially unsafe use of Ecto fragments with user input",
    language: "elixir",
    type: "sql_injection",
    severity: "high",
    cwe_id: "CWE-89",
    owasp_category: "A03:2021 - Injection",
    remediation: "Be careful with Ecto fragment usage. Ensure all user inputs are properly sanitized and use parameterized placeholders. Consider using Ecto query DSL instead of fragments when possible",
    confidence: "medium",
    framework: nil,
    regex_patterns: [],
    safe_usage_patterns: [],
    example_code: nil,
    fix_template: nil,
    tier_id: Map.get(tiers, "protected"),
    is_active: true,
    source: "rsolv",
    tags: ["elixir", "severity-high", "owasp-A03"],
    inserted_at: {:placeholder, :timestamp},
    updated_at: {:placeholder, :timestamp}
  },
  %{
    name: "Weak Password Hashing in Elixir",
    description: "Detects use of weak hashing algorithms for passwords",
    language: "elixir",
    type: "broken_authentication",
    severity: "high",
    cwe_id: "CWE-916",
    owasp_category: "A07:2021 - Identification and Authentication Failures",
    remediation: "Use Bcrypt, Argon2, or Pbkdf2 with appropriate cost factors in Elixir. For Bcrypt, use at least 12 rounds with the bcrypt_elixir library",
    confidence: "medium",
    framework: nil,
    regex_patterns: [":crypto\\.hash\\s*\\(\\s*:(?:md5|sha|sha1|sha256)\\s*,", "Base\\.encode\\d+\\s*\\(\\s*:crypto\\.hash\\s*\\(\\s*:(?:md5|sha|sha1|sha256)\\s*,"],
    safe_usage_patterns: [],
    example_code: nil,
    fix_template: nil,
    tier_id: Map.get(tiers, "protected"),
    is_active: true,
    source: "rsolv",
    tags: ["elixir", "severity-high", "owasp-A07"],
    inserted_at: {:placeholder, :timestamp},
    updated_at: {:placeholder, :timestamp}
  },
  %{
    name: "CORS Misconfiguration",
    description: "Detects overly permissive CORS configurations",
    language: "elixir",
    type: "security_misconfiguration",
    severity: "medium",
    cwe_id: "CWE-942",
    owasp_category: "A05:2021 - Security Misconfiguration",
    remediation: "Configure CORS with specific allowed origins instead of wildcards in Phoenix applications using CORSPlug",
    confidence: "medium",
    framework: nil,
    regex_patterns: [],
    safe_usage_patterns: [],
    example_code: nil,
    fix_template: nil,
    tier_id: Map.get(tiers, "protected"),
    is_active: true,
    source: "rsolv",
    tags: ["elixir", "severity-medium", "owasp-A05"],
    inserted_at: {:placeholder, :timestamp},
    updated_at: {:placeholder, :timestamp}
  },
  %{
    name: "Server-Side Request Forgery",
    description: "Detects SSRF vulnerabilities in HTTP clients",
    language: "elixir",
    type: "ssrf",
    severity: "high",
    cwe_id: "CWE-918",
    owasp_category: "A10:2021 - Server-Side Request Forgery",
    remediation: "Validate and whitelist URLs before making requests in Elixir. Use URI module in Elixir to parse and verify the domain",
    confidence: "medium",
    framework: nil,
    regex_patterns: [],
    safe_usage_patterns: [],
    example_code: nil,
    fix_template: nil,
    tier_id: Map.get(tiers, "protected"),
    is_active: true,
    source: "rsolv",
    tags: ["elixir", "severity-high", "owasp-A10"],
    inserted_at: {:placeholder, :timestamp},
    updated_at: {:placeholder, :timestamp}
  },
  %{
    name: "Weak Random Number Generation",
    description: "Detects use of weak random number generators for security purposes",
    language: "elixir",
    type: "weak_cryptography",
    severity: "medium",
    cwe_id: "CWE-338",
    owasp_category: "A02:2021 - Cryptographic Failures",
    remediation: "Use Elixir\\",
    confidence: "medium",
    framework: nil,
    regex_patterns: [":rand\\.uniform\\s*\\(", "Enum\\.random\\s*\\(", ":random\\.uniform\\s*\\("],
    safe_usage_patterns: [],
    example_code: nil,
    fix_template: nil,
    tier_id: Map.get(tiers, "protected"),
    is_active: true,
    source: "rsolv",
    tags: ["elixir", "severity-medium", "owasp-A02"],
    inserted_at: {:placeholder, :timestamp},
    updated_at: {:placeholder, :timestamp}
  },
  %{
    name: "CSRF Protection Disabled",
    description: "Detects disabled or misconfigured CSRF protection",
    language: "elixir",
    type: "csrf",
    severity: "medium",
    cwe_id: nil,
    owasp_category: nil,
    remediation: "Review and fix the security issue",
    confidence: "medium",
    framework: nil,
    regex_patterns: [],
    safe_usage_patterns: [],
    example_code: nil,
    fix_template: nil,
    tier_id: Map.get(tiers, "protected"),
    is_active: true,
    source: "rsolv",
    tags: ["elixir", "severity-medium"],
    inserted_at: {:placeholder, :timestamp},
    updated_at: {:placeholder, :timestamp}
  },
  %{
    name: "Missing Security Event Logging",
    description: "Detects missing logging for security-critical operations",
    language: "elixir",
    type: "insufficient_logging",
    severity: "medium",
    cwe_id: nil,
    owasp_category: nil,
    remediation: "Review and fix the security issue",
    confidence: "medium",
    framework: nil,
    regex_patterns: [],
    safe_usage_patterns: [],
    example_code: nil,
    fix_template: nil,
    tier_id: Map.get(tiers, "protected"),
    is_active: true,
    source: "rsolv",
    tags: ["elixir", "severity-medium"],
    inserted_at: {:placeholder, :timestamp},
    updated_at: {:placeholder, :timestamp}
  },
  %{
    name: "XML External Entity Injection",
    description: "Detects potential XXE vulnerabilities in XML parsing",
    language: "elixir",
    type: "xxe",
    severity: "high",
    cwe_id: "CWE-611",
    owasp_category: "A05:2021 - Security Misconfiguration",
    remediation: "Disable external entity processing in Elixir XML parsers. Use SweetXml or other safe Elixir XML parsing libraries with XXE protection enabled by default",
    confidence: "medium",
    framework: nil,
    regex_patterns: [":xmerl_scan\\.string\\s*\\("],
    safe_usage_patterns: [],
    example_code: nil,
    fix_template: nil,
    tier_id: Map.get(tiers, "protected"),
    is_active: true,
    source: "rsolv",
    tags: ["elixir", "severity-high", "owasp-A05"],
    inserted_at: {:placeholder, :timestamp},
    updated_at: {:placeholder, :timestamp}
  },
  %{
    name: "Template Injection",
    description: "Detects template injection vulnerabilities in EEx templates",
    language: "elixir",
    type: "template_injection",
    severity: "high",
    cwe_id: "CWE-94",
    owasp_category: "A03:2021 - Injection",
    remediation: "Never evaluate user-provided templates in Elixir. Use static EEx templates in Phoenix and pass data as variables",
    confidence: "medium",
    framework: nil,
    regex_patterns: [],
    safe_usage_patterns: [],
    example_code: nil,
    fix_template: nil,
    tier_id: Map.get(tiers, "protected"),
    is_active: true,
    source: "rsolv",
    tags: ["elixir", "severity-high", "owasp-A03"],
    inserted_at: {:placeholder, :timestamp},
    updated_at: {:placeholder, :timestamp}
  },
  %{
    name: "Use of Vulnerable Dependencies",
    description: "Detects potentially vulnerable Elixir/Erlang functions",
    language: "elixir",
    type: "vulnerable_components",
    severity: "medium",
    cwe_id: "CWE-1104",
    owasp_category: "A06:2021 - Vulnerable and Outdated Components",
    remediation: "Use modern Elixir alternatives: System.monotonic_time instead of :erlang.now, :rand instead of :random, and always use safe option with binary_to_term",
    confidence: "medium",
    framework: nil,
    regex_patterns: [":erlang\\.now\\s*\\(\\)", ":random\\."],
    safe_usage_patterns: [],
    example_code: nil,
    fix_template: nil,
    tier_id: Map.get(tiers, "protected"),
    is_active: true,
    source: "rsolv",
    tags: ["elixir", "severity-medium", "owasp-A06"],
    inserted_at: {:placeholder, :timestamp},
    updated_at: {:placeholder, :timestamp}
  },
  %{
    name: "Potential DoS via Atom Exhaustion",
    description: "Detects patterns that could lead to atom table exhaustion",
    language: "elixir",
    type: "denial_of_service",
    severity: "medium",
    cwe_id: "CWE-400",
    owasp_category: "A06:2021 - Vulnerable and Outdated Components",
    remediation: "Atoms are not garbage collected in Elixir. Use String.to_existing_atom/1 or maintain a whitelist of allowed atoms in Phoenix",
    confidence: "medium",
    framework: nil,
    regex_patterns: [],
    safe_usage_patterns: [],
    example_code: nil,
    fix_template: nil,
    tier_id: Map.get(tiers, "protected"),
    is_active: true,
    source: "rsolv",
    tags: ["elixir", "severity-medium", "owasp-A06"],
    inserted_at: {:placeholder, :timestamp},
    updated_at: {:placeholder, :timestamp}
  },
  %{
    name: "Open Redirect Vulnerability",
    description: "Detects open redirect vulnerabilities in Phoenix applications",
    language: "elixir",
    type: "open_redirect",
    severity: "medium",
    cwe_id: "CWE-601",
    owasp_category: "A01:2021 - Broken Access Control",
    remediation: "Validate redirect URLs against a whitelist in Phoenix. Never redirect to user-provided URLs without validation in Elixir web apps",
    confidence: "medium",
    framework: nil,
    regex_patterns: [],
    safe_usage_patterns: [],
    example_code: nil,
    fix_template: nil,
    tier_id: Map.get(tiers, "protected"),
    is_active: true,
    source: "rsolv",
    tags: ["elixir", "severity-medium", "owasp-A01"],
    inserted_at: {:placeholder, :timestamp},
    updated_at: {:placeholder, :timestamp}
  },
  %{
    name: "Missing Strong Parameters",
    description: "Rails controllers using params without permit() allowing mass assignment",
    language: "ruby",
    type: "mass_assignment",
    severity: "high",
    cwe_id: "CWE-915",
    owasp_category: "A01:2021 - Broken Access Control",
    remediation: "Use strong parameters with permit(): params.require(:model).permit(:field1, :field2). Never use permit! in production.",
    confidence: "medium",
    framework: nil,
    regex_patterns: ["\\.(create|update|update_attributes|assign_attributes)\\s*\\(\\s*params(?!\\s*\\.\\s*(require|permit))", "User\\.new\\s*\\(\\s*params\\[", "\\.permit!\\s*\\)", "\\.(create!|update!)\\s*\\(\\s*params\\[", "\\.insert_all\\s*\\(\\s*params\\[", "\\.upsert_all\\s*\\(\\s*params\\["],
    safe_usage_patterns: [],
    example_code: nil,
    fix_template: nil,
    tier_id: Map.get(tiers, "protected"),
    is_active: true,
    source: "rsolv",
    tags: ["ruby", "severity-high", "owasp-A01"],
    inserted_at: {:placeholder, :timestamp},
    updated_at: {:placeholder, :timestamp}
  },
  %{
    name: "Dangerous attr_accessible Usage",
    description: "Overly permissive attr_accessible in older Rails versions or missing protection",
    language: "ruby",
    type: "mass_assignment",
    severity: "high",
    cwe_id: "CWE-915",
    owasp_category: "A01:2021 - Broken Access Control",
    remediation: "Upgrade to Rails 4+ and use strong parameters. If using older Rails, carefully restrict attr_accessible fields.",
    confidence: "medium",
    framework: nil,
    regex_patterns: [],
    safe_usage_patterns: [],
    example_code: nil,
    fix_template: nil,
    tier_id: Map.get(tiers, "protected"),
    is_active: true,
    source: "rsolv",
    tags: ["ruby", "severity-high", "owasp-A01"],
    inserted_at: {:placeholder, :timestamp},
    updated_at: {:placeholder, :timestamp}
  },
  %{
    name: "Rails Template XSS",
    description: "Cross-site scripting through unsafe template output",
    language: "ruby",
    type: "xss",
    severity: "medium",
    cwe_id: "CWE-79",
    owasp_category: "A03:2021 - Injection",
    remediation: "Use Rails built-in escaping or Rails sanitize helpers: sanitize(), strip_tags(), or escape HTML entities. Remove raw() and html_safe calls on user content.",
    confidence: "medium",
    framework: nil,
    regex_patterns: [],
    safe_usage_patterns: [],
    example_code: nil,
    fix_template: nil,
    tier_id: Map.get(tiers, "protected"),
    is_active: true,
    source: "rsolv",
    tags: ["ruby", "severity-medium", "owasp-A03"],
    inserted_at: {:placeholder, :timestamp},
    updated_at: {:placeholder, :timestamp}
  },
  %{
    name: "Dangerous Production Configuration",
    description: "Development settings enabled in production environment",
    language: "ruby",
    type: "debug_mode",
    severity: "medium",
    cwe_id: "CWE-489",
    owasp_category: "A05:2021 - Security Misconfiguration",
    remediation: "Ensure Rails production environment has consider_all_requests_local=false, debug gems removed, and proper Rails caching enabled",
    confidence: "medium",
    framework: nil,
    regex_patterns: ["config\\.consider_all_requests_local\\s*=\\s*true", "config\\.action_controller\\.perform_caching\\s*=\\s*false", "config\\.log_level\\s*=\\s*:debug", "config\\.eager_load\\s*=\\s*false", "config\\.cache_classes\\s*=\\s*false"],
    safe_usage_patterns: [],
    example_code: nil,
    fix_template: nil,
    tier_id: Map.get(tiers, "protected"),
    is_active: true,
    source: "rsolv",
    tags: ["ruby", "severity-medium", "owasp-A05"],
    inserted_at: {:placeholder, :timestamp},
    updated_at: {:placeholder, :timestamp}
  },
  %{
    name: "Insecure CORS Configuration",
    description: "Overly permissive Cross-Origin Resource Sharing configuration",
    language: "ruby",
    type: "security_misconfiguration",
    severity: "medium",
    cwe_id: "CWE-346",
    owasp_category: "A05:2021 - Security Misconfiguration",
    remediation: "Specify explicit origins, headers, and methods in Rails CORS. Never use credentials: true with origins: ",
    confidence: "medium",
    framework: nil,
    regex_patterns: [],
    safe_usage_patterns: [],
    example_code: nil,
    fix_template: nil,
    tier_id: Map.get(tiers, "protected"),
    is_active: true,
    source: "rsolv",
    tags: ["ruby", "severity-medium", "owasp-A05"],
    inserted_at: {:placeholder, :timestamp},
    updated_at: {:placeholder, :timestamp}
  },
  %{
    name: "Session Fixation Vulnerability",
    description: "Missing session regeneration after authentication allowing session fixation",
    language: "ruby",
    type: "broken_authentication",
    severity: "medium",
    cwe_id: "CWE-384",
    owasp_category: "A07:2021 - Identification and Authentication Failures",
    remediation: "Call Rails reset_session or session.regenerate before setting authentication session variables in Rails controllers",
    confidence: "medium",
    framework: nil,
    regex_patterns: [],
    safe_usage_patterns: [],
    example_code: nil,
    fix_template: nil,
    tier_id: Map.get(tiers, "public"),
    is_active: true,
    source: "rsolv",
    tags: ["ruby", "severity-medium", "owasp-A07"],
    inserted_at: {:placeholder, :timestamp},
    updated_at: {:placeholder, :timestamp}
  },
  %{
    name: "Sensitive Data in Session",
    description: "Storing sensitive information in session cookies",
    language: "ruby",
    type: "sensitive_data_exposure",
    severity: "high",
    cwe_id: "CWE-200",
    owasp_category: "A02:2021 - Cryptographic Failures",
    remediation: "Store only non-sensitive identifiers in Rails sessions. Keep sensitive data in secure server-side storage, not Rails session cookies.",
    confidence: "medium",
    framework: nil,
    regex_patterns: [],
    safe_usage_patterns: [],
    example_code: nil,
    fix_template: nil,
    tier_id: Map.get(tiers, "protected"),
    is_active: true,
    source: "rsolv",
    tags: ["ruby", "severity-high", "owasp-A02"],
    inserted_at: {:placeholder, :timestamp},
    updated_at: {:placeholder, :timestamp}
  },
  %{
    name: "Django Template Injection",
    description: "Server-side template injection through dynamic template compilation",
    language: "python",
    type: "template_injection",
    severity: "critical",
    cwe_id: "CWE-94",
    owasp_category: "A03:2021 - Injection",
    remediation: "Never compile user input as Django templates. Use static Django templates with context variables and Django template system.",
    confidence: "medium",
    framework: nil,
    regex_patterns: [],
    safe_usage_patterns: [],
    example_code: nil,
    fix_template: nil,
    tier_id: Map.get(tiers, "protected"),
    is_active: true,
    source: "rsolv",
    tags: ["python", "severity-critical", "owasp-A03"],
    inserted_at: {:placeholder, :timestamp},
    updated_at: {:placeholder, :timestamp}
  },
  %{
    name: "Dangerous Django Debug Settings",
    description: "Debug mode and development settings enabled in production",
    language: "python",
    type: "debug_mode",
    severity: "high",
    cwe_id: "CWE-489",
    owasp_category: "A05:2021 - Security Misconfiguration",
    remediation: "Set Django DEBUG=False, configure Django ALLOWED_HOSTS, remove debug apps from Django INSTALLED_APPS, and use Django environment-specific settings",
    confidence: "medium",
    framework: nil,
    regex_patterns: ["DEBUG\\s*=\\s*True"],
    safe_usage_patterns: [],
    example_code: nil,
    fix_template: nil,
    tier_id: Map.get(tiers, "protected"),
    is_active: true,
    source: "rsolv",
    tags: ["python", "severity-high", "owasp-A05"],
    inserted_at: {:placeholder, :timestamp},
    updated_at: {:placeholder, :timestamp}
  },
  %{
    name: "Insecure Django Session Configuration",
    description: "Django session and cookie settings without proper security flags",
    language: "python",
    type: "security_misconfiguration",
    severity: "medium",
    cwe_id: "CWE-614",
    owasp_category: "A05:2021 - Security Misconfiguration",
    remediation: "Set Django session secure=True, httponly=True, and samesite=",
    confidence: "medium",
    framework: nil,
    regex_patterns: ["SESSION_COOKIE_SECURE\\s*=\\s*False", "SESSION_COOKIE_HTTPONLY\\s*=\\s*False", "SESSION_COOKIE_SAMESITE\\s*=\\s*None", "CSRF_COOKIE_SECURE\\s*=\\s*False", "CSRF_COOKIE_HTTPONLY\\s*=\\s*False", "SESSION_EXPIRE_AT_BROWSER_CLOSE\\s*=\\s*False", "SESSION_COOKIE_AGE\\s*=\\s*31536000", "SESSION_SAVE_EVERY_REQUEST\\s*=\\s*False"],
    safe_usage_patterns: [],
    example_code: nil,
    fix_template: nil,
    tier_id: Map.get(tiers, "protected"),
    is_active: true,
    source: "rsolv",
    tags: ["python", "severity-medium", "owasp-A05"],
    inserted_at: {:placeholder, :timestamp},
    updated_at: {:placeholder, :timestamp}
  },
  %{
    name: "Missing Django Security Middleware",
    description: "Missing or incorrectly configured security middleware",
    language: "python",
    type: "security_misconfiguration",
    severity: "medium",
    cwe_id: "CWE-693",
    owasp_category: "A05:2021 - Security Misconfiguration",
    remediation: "Add Django SecurityMiddleware and CsrfViewMiddleware to Django MIDDLEWARE in correct order, enable HTTPS redirects in Django settings",
    confidence: "medium",
    framework: nil,
    regex_patterns: [],
    safe_usage_patterns: [],
    example_code: nil,
    fix_template: nil,
    tier_id: Map.get(tiers, "protected"),
    is_active: true,
    source: "rsolv",
    tags: ["python", "severity-medium", "owasp-A05"],
    inserted_at: {:placeholder, :timestamp},
    updated_at: {:placeholder, :timestamp}
  },
  %{
    name: "Django Broken Authentication",
    description: "Weak authentication patterns and missing validation",
    language: "python",
    type: "broken_authentication",
    severity: "high",
    cwe_id: "CWE-287",
    owasp_category: "A07:2021 - Identification and Authentication Failures",
    remediation: "Use Django built-in authentication system, require Django login decorators, implement Django password validators, avoid hardcoded credentials",
    confidence: "medium",
    framework: nil,
    regex_patterns: ["def\\s+\\w*admin\\w*.*?\\(.*?request.*?\\):(?!.*@login_required)(?!.*request\\.user\\.is_authenticated)"],
    safe_usage_patterns: [],
    example_code: nil,
    fix_template: nil,
    tier_id: Map.get(tiers, "protected"),
    is_active: true,
    source: "rsolv",
    tags: ["python", "severity-high", "owasp-A07"],
    inserted_at: {:placeholder, :timestamp},
    updated_at: {:placeholder, :timestamp}
  },
  %{
    name: "Django Authorization Bypass",
    description: "Missing or improper authorization checks in views",
    language: "python",
    type: "broken_access_control",
    severity: "high",
    cwe_id: "CWE-285",
    owasp_category: "A01:2021 - Broken Access Control",
    remediation: "Use Django @login_required, @permission_required decorators, implement Django object-level permissions, validate ownership in Django views",
    confidence: "medium",
    framework: nil,
    regex_patterns: [],
    safe_usage_patterns: [],
    example_code: nil,
    fix_template: nil,
    tier_id: Map.get(tiers, "protected"),
    is_active: true,
    source: "rsolv",
    tags: ["python", "severity-high", "owasp-A01"],
    inserted_at: {:placeholder, :timestamp},
    updated_at: {:placeholder, :timestamp}
  },
  %{
    name: "Django Mass Assignment",
    description: "Mass assignment vulnerabilities in Django model operations",
    language: "python",
    type: "mass_assignment",
    severity: "high",
    cwe_id: "CWE-915",
    owasp_category: "A01:2021 - Broken Access Control",
    remediation: "Use ModelForm with explicit fields, validate input, implement field whitelisting",
    confidence: "medium",
    framework: nil,
    regex_patterns: ["User\\.objects\\.create\\s*\\(\\s*\\*\\*\\s*request\\.POST\\s*\\)", "User\\s*\\(\\s*\\*\\*\\s*request\\.POST\\.dict\\(\\)\\s*\\)\\.save\\(\\)", "User\\.objects\\.bulk_create\\s*\\(\\s*\\[\\s*User\\s*\\(\\s*\\*\\*\\s*data\\s*\\)", "User\\.objects\\.filter\\s*\\(.*?\\)\\.update\\s*\\(\\s*\\*\\*\\s*request\\.POST\\s*\\)", "user\\.__dict__\\.update\\s*\\(\\s*request\\.POST\\s*\\)", "form\\s*=\\s*ModelForm\\s*\\(\\s*request\\.POST.*?instance\\s*=\\s*user\\s*\\)", "class\\s+\\w+Form\\s*\\(\\s*ModelForm\\s*\\):.*?class\\s+Meta:.*?model\\s*=\\s*\\w+(?!.*fields)"],
    safe_usage_patterns: [],
    example_code: nil,
    fix_template: nil,
    tier_id: Map.get(tiers, "protected"),
    is_active: true,
    source: "rsolv",
    tags: ["python", "severity-high", "owasp-A01"],
    inserted_at: {:placeholder, :timestamp},
    updated_at: {:placeholder, :timestamp}
  },
  %{
    name: "Unsafe Django URL Patterns",
    description: "Overly permissive URL patterns allowing path traversal",
    language: "python",
    type: "path_traversal",
    severity: "high",
    cwe_id: "CWE-22",
    owasp_category: "A01:2021 - Broken Access Control",
    remediation: "Use specific Django URL patterns, validate path parameters in Django views, restrict file access to safe directories",
    confidence: "medium",
    framework: nil,
    regex_patterns: [],
    safe_usage_patterns: [],
    example_code: nil,
    fix_template: nil,
    tier_id: Map.get(tiers, "protected"),
    is_active: true,
    source: "rsolv",
    tags: ["python", "severity-high", "owasp-A01"],
    inserted_at: {:placeholder, :timestamp},
    updated_at: {:placeholder, :timestamp}
  },
  %{
    name: "CVE-2021-33203 - Directory Traversal in Static Files",
    description: "Directory traversal vulnerability in Django static file serving",
    language: "python",
    type: "path_traversal",
    severity: "high",
    cwe_id: "CWE-22",
    owasp_category: "A01:2021 - Broken Access Control",
    remediation: "Validate file paths, use Django\\",
    confidence: "medium",
    framework: nil,
    regex_patterns: [],
    safe_usage_patterns: [],
    example_code: nil,
    fix_template: nil,
    tier_id: Map.get(tiers, "ai"),
    is_active: true,
    source: "rsolv",
    tags: ["python", "severity-high", "owasp-A01"],
    inserted_at: {:placeholder, :timestamp},
    updated_at: {:placeholder, :timestamp}
  },
  %{
    name: "Log4Shell Vulnerability (CVE-2021-44228)",
    description: "Detects potentially vulnerable Log4j versions (CVE-2021-44228 - Log4Shell)",
    language: "java",
    type: "vulnerable_components",
    severity: "critical",
    cwe_id: "CWE-502",
    owasp_category: "A06:2021 – Vulnerable and Outdated Components",
    remediation: "Update Log4j to version 2.17.0 or later to patch Log4Shell vulnerability",
    confidence: "medium",
    framework: nil,
    regex_patterns: [],
    safe_usage_patterns: [],
    example_code: nil,
    fix_template: nil,
    tier_id: Map.get(tiers, "ai"),
    is_active: true,
    source: "rsolv",
    tags: ["java", "severity-critical", "owasp-A06"],
    inserted_at: {:placeholder, :timestamp},
    updated_at: {:placeholder, :timestamp}
  }
]

# Insert all patterns
timestamp = NaiveDateTime.utc_now() |> NaiveDateTime.truncate(:second)
{count, _} = Repo.insert_all(SecurityPattern, patterns_data, placeholders: %{timestamp: timestamp})

IO.puts("✅ Successfully loaded #{count} security patterns!")

# Print final summary
IO.puts("\n📊 Final Summary:")
Enum.each(tiers, fn {tier_name, tier_id} ->
  count = Repo.one(from p in SecurityPattern, where: p.tier_id == ^tier_id, select: count(p.id))
  IO.puts("  #{tier_name}: #{count} patterns")
end)

total = Repo.one(from p in SecurityPattern, select: count(p.id))
IO.puts("\n🎯 Total patterns in database: #{total}")