# Security Patterns Seed File
# Generated: 2025-06-08T03:47:12.579Z
# Total Patterns: 39

alias RsolvApi.Repo
alias RsolvApi.Security.{SecurityPattern, PatternTier}

IO.puts("🔍 Loading security patterns...")

# Clear existing patterns
Repo.delete_all(SecurityPattern)

# Get tier IDs
tiers = Repo.all(PatternTier) |> Enum.map(&{&1.name, &1.id}) |> Enum.into(%{})

# Pattern distribution:
# protected: 39 patterns

# Insert patterns
patterns = [
  %{
    name: "TypeScript Non-Null Assertion",
    description: "Detects unsafe non-null assertions that may cause runtime errors",
    language: "typescript",
    type: "null_pointer_dereference",
    severity: "medium",
    cwe_id: "CWE-476",
    owasp_category: "A04:2021 - Insecure Design",
    remediation: "Use proper null checks instead of non-null assertions",
    confidence: "medium",
    framework: nil,
    regex_patterns: ["\\w+!\\.(?!length|toString|valueOf)"],
    safe_usage_patterns: [],
    example_code: nil,
    fix_template: nil,
    tier_id: Map.get(tiers, "protected"),
    is_active: true,
    source: "rsolv",
    tags: ["typescript", "severity-medium", "owasp-A04"],
    inserted_at: {:placeholder, :timestamp},
    updated_at: {:placeholder, :timestamp}
  },
  %{
    name: "GraphQL Introspection Enabled",
    description: "Detects GraphQL introspection enabled in production",
    language: "javascript",
    type: "information_disclosure",
    severity: "medium",
    cwe_id: "CWE-200",
    owasp_category: "A01:2021 - Broken Access Control",
    remediation: "Disable GraphQL introspection in production environments",
    confidence: "medium",
    framework: nil,
    regex_patterns: ["introspection:\\s*true", "GraphQLSchema.*introspection:\\s*true"],
    safe_usage_patterns: [],
    example_code: nil,
    fix_template: nil,
    tier_id: Map.get(tiers, "protected"),
    is_active: true,
    source: "rsolv",
    tags: ["javascript", "severity-medium", "owasp-A01"],
    inserted_at: {:placeholder, :timestamp},
    updated_at: {:placeholder, :timestamp}
  },
  %{
    name: "Electron Node Integration Enabled",
    description: "Detects unsafe Electron configurations with Node integration",
    language: "javascript",
    type: "security_misconfiguration",
    severity: "critical",
    cwe_id: "CWE-829",
    owasp_category: "A05:2021 - Security Misconfiguration",
    remediation: "Disable Node integration and enable context isolation",
    confidence: "medium",
    framework: nil,
    regex_patterns: ["nodeIntegration:\\s*true", "contextIsolation:\\s*false", "webSecurity:\\s*false"],
    safe_usage_patterns: [],
    example_code: nil,
    fix_template: nil,
    tier_id: Map.get(tiers, "protected"),
    is_active: true,
    source: "rsolv",
    tags: ["javascript", "severity-critical", "owasp-A05"],
    inserted_at: {:placeholder, :timestamp},
    updated_at: {:placeholder, :timestamp}
  },
  %{
    name: "LDAP Injection",
    description: "Detects LDAP injection vulnerabilities",
    language: "javascript",
    type: "ldap_injection",
    severity: "high",
    cwe_id: "CWE-90",
    owasp_category: "A03:2021 - Injection",
    remediation: "Use parameterized LDAP queries and escape special characters",
    confidence: "medium",
    framework: nil,
    regex_patterns: ["ldap.*search.*filter.*\\+.*req\\."],
    safe_usage_patterns: [],
    example_code: nil,
    fix_template: nil,
    tier_id: Map.get(tiers, "protected"),
    is_active: true,
    source: "rsolv",
    tags: ["javascript", "severity-high", "owasp-A03"],
    inserted_at: {:placeholder, :timestamp},
    updated_at: {:placeholder, :timestamp}
  },
  %{
    name: "Missing Authentication in Rails Controller",
    description: "Detects Rails controllers without authentication filters",
    language: "ruby",
    type: "broken_access_control",
    severity: "high",
    cwe_id: "CWE-862",
    owasp_category: "A01:2021 - Broken Access Control",
    remediation: "Add before_action :authenticate_user! to protect sensitive actions",
    confidence: "medium",
    framework: nil,
    regex_patterns: ["class\\s+\\w+Controller\\s*<\\s*ApplicationController(?:(?!before_action|before_filter|authenticate).)*end", "def\\s+(admin|delete|update|create)(?:(?!current_user|logged_in|authenticate).)*end"],
    safe_usage_patterns: [],
    example_code: nil,
    fix_template: nil,
    tier_id: Map.get(tiers, "protected"),
    is_active: true,
    source: "rsolv",
    tags: ["ruby", "severity-high", "owasp-A01"],
    inserted_at: {:placeholder, :timestamp},
    updated_at: {:placeholder, :timestamp}
  },
  %{
    name: "Mass Assignment Vulnerability",
    description: "Detects unfiltered params in model operations",
    language: "ruby",
    type: "mass_assignment",
    severity: "high",
    cwe_id: "CWE-915",
    owasp_category: "A01:2021 - Broken Access Control",
    remediation: "Use strong parameters: params.require(:user).permit(:name, :email)",
    confidence: "medium",
    framework: nil,
    regex_patterns: ["\\.(create|update|update_attributes|assign_attributes)\\s*\\(\\s*params(?!\\s*\\.\\s*(require|permit))", "User\\.new\\s*\\(\\s*params\\["],
    safe_usage_patterns: [],
    example_code: nil,
    fix_template: nil,
    tier_id: Map.get(tiers, "protected"),
    is_active: true,
    source: "rsolv",
    tags: ["ruby", "severity-high", "owasp-A01"],
    inserted_at: {:placeholder, :timestamp},
    updated_at: {:placeholder, :timestamp}
  },
  %{
    name: "Weak Cryptography - MD5",
    description: "MD5 is cryptographically broken and should not be used",
    language: "ruby",
    type: "weak_cryptography",
    severity: "medium",
    cwe_id: "CWE-327",
    owasp_category: "A02:2021 - Cryptographic Failures",
    remediation: "Use SHA-256 or SHA-3: Digest::SHA256.hexdigest(data)",
    confidence: "medium",
    framework: nil,
    regex_patterns: ["Digest::MD5", "OpenSSL::Digest::MD5", "\\.md5\\("],
    safe_usage_patterns: [],
    example_code: nil,
    fix_template: nil,
    tier_id: Map.get(tiers, "protected"),
    is_active: true,
    source: "rsolv",
    tags: ["ruby", "severity-medium", "owasp-A02"],
    inserted_at: {:placeholder, :timestamp},
    updated_at: {:placeholder, :timestamp}
  },
  %{
    name: "Weak Random Number Generation",
    description: "Using predictable random number generation",
    language: "ruby",
    type: "weak_cryptography",
    severity: "medium",
    cwe_id: "CWE-330",
    owasp_category: "A04:2021 - Insecure Design",
    remediation: "Use SecureRandom for security-sensitive randomness",
    confidence: "medium",
    framework: nil,
    regex_patterns: ["\\brand\\s*\\(", "Random\\.rand(?!\\s*\\(\\s*SecureRandom)", "\\bsrand\\s*\\("],
    safe_usage_patterns: [],
    example_code: nil,
    fix_template: nil,
    tier_id: Map.get(tiers, "protected"),
    is_active: true,
    source: "rsolv",
    tags: ["ruby", "severity-medium", "owasp-A04"],
    inserted_at: {:placeholder, :timestamp},
    updated_at: {:placeholder, :timestamp}
  },
  %{
    name: "Debug Mode Enabled",
    description: "Debug mode exposes sensitive information",
    language: "ruby",
    type: "debug_mode",
    severity: "medium",
    cwe_id: "CWE-489",
    owasp_category: "A05:2021 - Security Misconfiguration",
    remediation: "Remove debug statements and disable debug mode in production",
    confidence: "medium",
    framework: nil,
    regex_patterns: ["config\\.consider_all_requests_local\\s*=\\s*true", "\\bbyebug\\b", "\\bdebugger\\b", "binding\\.pry"],
    safe_usage_patterns: [],
    example_code: nil,
    fix_template: nil,
    tier_id: Map.get(tiers, "protected"),
    is_active: true,
    source: "rsolv",
    tags: ["ruby", "severity-medium", "owasp-A05"],
    inserted_at: {:placeholder, :timestamp},
    updated_at: {:placeholder, :timestamp}
  },
  %{
    name: "Use of eval()",
    description: "eval() can execute arbitrary code",
    language: "ruby",
    type: "vulnerable_components",
    severity: "high",
    cwe_id: "CWE-95",
    owasp_category: "A06:2021 - Vulnerable and Outdated Components",
    remediation: "Avoid eval() or validate/sanitize input thoroughly",
    confidence: "medium",
    framework: nil,
    regex_patterns: ["\\beval\\s*\\(", "instance_eval", "class_eval", "module_eval"],
    safe_usage_patterns: [],
    example_code: nil,
    fix_template: nil,
    tier_id: Map.get(tiers, "protected"),
    is_active: true,
    source: "rsolv",
    tags: ["ruby", "severity-high", "owasp-A06"],
    inserted_at: {:placeholder, :timestamp},
    updated_at: {:placeholder, :timestamp}
  },
  %{
    name: "Weak Password Storage",
    description: "Passwords stored without proper hashing",
    language: "ruby",
    type: "broken_authentication",
    severity: "critical",
    cwe_id: "CWE-256",
    owasp_category: "A07:2021 - Identification and Authentication Failures",
    remediation: "Use BCrypt for password hashing",
    confidence: "medium",
    framework: nil,
    regex_patterns: ["password\\s*=\\s*Digest::(MD5|SHA1)", "user\\.password\\s*=\\s*params", "password.*?\\.downcase(?!.*bcrypt)"],
    safe_usage_patterns: [],
    example_code: nil,
    fix_template: nil,
    tier_id: Map.get(tiers, "protected"),
    is_active: true,
    source: "rsolv",
    tags: ["ruby", "severity-critical", "owasp-A07"],
    inserted_at: {:placeholder, :timestamp},
    updated_at: {:placeholder, :timestamp}
  },
  %{
    name: "Unsafe Deserialization with Marshal",
    description: "Marshal.load can execute arbitrary code",
    language: "ruby",
    type: "insecure_deserialization",
    severity: "critical",
    cwe_id: "CWE-502",
    owasp_category: "A08:2021 - Software and Data Integrity Failures",
    remediation: "Use JSON or MessagePack for serialization",
    confidence: "medium",
    framework: nil,
    regex_patterns: ["Marshal\\.load", "Marshal\\.restore"],
    safe_usage_patterns: [],
    example_code: nil,
    fix_template: nil,
    tier_id: Map.get(tiers, "protected"),
    is_active: true,
    source: "rsolv",
    tags: ["ruby", "severity-critical", "owasp-A08"],
    inserted_at: {:placeholder, :timestamp},
    updated_at: {:placeholder, :timestamp}
  },
  %{
    name: "Unsafe YAML Loading",
    description: "YAML.load can execute arbitrary code",
    language: "ruby",
    type: "insecure_deserialization",
    severity: "high",
    cwe_id: "CWE-502",
    owasp_category: "A08:2021 - Software and Data Integrity Failures",
    remediation: "Use YAML.safe_load for untrusted input",
    confidence: "medium",
    framework: nil,
    regex_patterns: ["YAML\\.load(?!_file|_stream)", "Psych\\.load(?!_file|_stream)"],
    safe_usage_patterns: [],
    example_code: nil,
    fix_template: nil,
    tier_id: Map.get(tiers, "protected"),
    is_active: true,
    source: "rsolv",
    tags: ["ruby", "severity-high", "owasp-A08"],
    inserted_at: {:placeholder, :timestamp},
    updated_at: {:placeholder, :timestamp}
  },
  %{
    name: "Insufficient Security Logging",
    description: "Missing logging for security-relevant events",
    language: "ruby",
    type: "insufficient_logging",
    severity: "low",
    cwe_id: "CWE-778",
    owasp_category: "A09:2021 - Security Logging and Monitoring Failures",
    remediation: "Log security events and errors appropriately",
    confidence: "medium",
    framework: nil,
    regex_patterns: ["rescue\\s*(?:Exception|StandardError)?\\s*(?:=>)?\\s*\\w*\\s*\\n\\s*end", "rescue\\s*\\n\\s*nil\\s*\\n\\s*end"],
    safe_usage_patterns: [],
    example_code: nil,
    fix_template: nil,
    tier_id: Map.get(tiers, "protected"),
    is_active: true,
    source: "rsolv",
    tags: ["ruby", "severity-low", "owasp-A09"],
    inserted_at: {:placeholder, :timestamp},
    updated_at: {:placeholder, :timestamp}
  },
  %{
    name: "SSRF via open-uri",
    description: "Unvalidated URLs in open() can lead to SSRF",
    language: "ruby",
    type: "open_redirect",
    severity: "high",
    cwe_id: "CWE-918",
    owasp_category: "A10:2021 - Server-Side Request Forgery",
    remediation: "Validate URLs against allowlist before making requests",
    confidence: "medium",
    framework: nil,
    regex_patterns: ["open\\s*\\(\\s*params", "URI\\.open\\s*\\(\\s*params", "Net::HTTP\\.get.*params"],
    safe_usage_patterns: [],
    example_code: nil,
    fix_template: nil,
    tier_id: Map.get(tiers, "protected"),
    is_active: true,
    source: "rsolv",
    tags: ["ruby", "severity-high", "owasp-A10"],
    inserted_at: {:placeholder, :timestamp},
    updated_at: {:placeholder, :timestamp}
  },
  %{
    name: "XSS in ERB Templates",
    description: "Using raw() or html_safe without sanitization",
    language: "ruby",
    type: "xss",
    severity: "medium",
    cwe_id: "CWE-79",
    owasp_category: "A03:2021 - Injection",
    remediation: "Use Rails sanitize helpers or escape output by default",
    confidence: "medium",
    framework: nil,
    regex_patterns: ["<%=\\s*raw\\s+", "\\.html_safe(?!.*sanitize)", "<%==\\s*\\w+"],
    safe_usage_patterns: [],
    example_code: nil,
    fix_template: nil,
    tier_id: Map.get(tiers, "protected"),
    is_active: true,
    source: "rsolv",
    tags: ["ruby", "severity-medium", "owasp-A03"],
    inserted_at: {:placeholder, :timestamp},
    updated_at: {:placeholder, :timestamp}
  },
  %{
    name: "Open Redirect",
    description: "Unvalidated redirects can lead to phishing",
    language: "ruby",
    type: "open_redirect",
    severity: "medium",
    cwe_id: "CWE-601",
    owasp_category: "A01:2021 - Broken Access Control",
    remediation: "Validate redirect URLs against an allowlist",
    confidence: "medium",
    framework: nil,
    regex_patterns: ["redirect_to\\s+params", "redirect_to\\s+request\\.(referrer|referer)"],
    safe_usage_patterns: [],
    example_code: nil,
    fix_template: nil,
    tier_id: Map.get(tiers, "protected"),
    is_active: true,
    source: "rsolv",
    tags: ["ruby", "severity-medium", "owasp-A01"],
    inserted_at: {:placeholder, :timestamp},
    updated_at: {:placeholder, :timestamp}
  },
  %{
    name: "Weak Password Hashing in Elixir",
    description: "Detects use of weak hashing algorithms for passwords",
    language: "elixir",
    type: "broken_authentication",
    severity: "high",
    cwe_id: "CWE-916",
    owasp_category: "A07:2021 - Identification and Authentication Failures",
    remediation: "Use Bcrypt, Argon2, or Pbkdf2 with appropriate cost factors in Elixir. For Bcrypt, use at least 12 rounds with the bcrypt_elixir library",
    confidence: "medium",
    framework: nil,
    regex_patterns: [":crypto\\.hash\\s*\\(\\s*:(?:md5|sha|sha1|sha256)\\s*,", "Base\\.encode\\d+\\s*\\(\\s*:crypto\\.hash\\s*\\(\\s*:(?:md5|sha|sha1|sha256)\\s*,"],
    safe_usage_patterns: [],
    example_code: nil,
    fix_template: nil,
    tier_id: Map.get(tiers, "protected"),
    is_active: true,
    source: "rsolv",
    tags: ["elixir", "severity-high", "owasp-A07"],
    inserted_at: {:placeholder, :timestamp},
    updated_at: {:placeholder, :timestamp}
  },
  %{
    name: "Unsafe Atom Creation",
    description: "Detects dynamic atom creation from user input which can lead to memory exhaustion",
    language: "elixir",
    type: "insecure_deserialization",
    severity: "medium",
    cwe_id: "CWE-502",
    owasp_category: "A08:2021 - Software and Data Integrity Failures",
    remediation: "Use Elixir\\",
    confidence: "medium",
    framework: nil,
    regex_patterns: ["String\\.to_atom\\s*\\("],
    safe_usage_patterns: [],
    example_code: nil,
    fix_template: nil,
    tier_id: Map.get(tiers, "protected"),
    is_active: true,
    source: "rsolv",
    tags: ["elixir", "severity-medium", "owasp-A08"],
    inserted_at: {:placeholder, :timestamp},
    updated_at: {:placeholder, :timestamp}
  },
  %{
    name: "Unsafe Code Evaluation",
    description: "Detects dynamic code evaluation vulnerabilities",
    language: "elixir",
    type: "insecure_deserialization",
    severity: "critical",
    cwe_id: "CWE-94",
    owasp_category: "A08:2021 - Software and Data Integrity Failures",
    remediation: "Avoid dynamic code evaluation in Elixir. If necessary, strictly validate and sandbox the execution using proper Elixir patterns",
    confidence: "medium",
    framework: nil,
    regex_patterns: ["Code\\.eval_string\\s*\\(", "Code\\.eval_quoted\\s*\\("],
    safe_usage_patterns: [],
    example_code: nil,
    fix_template: nil,
    tier_id: Map.get(tiers, "protected"),
    is_active: true,
    source: "rsolv",
    tags: ["elixir", "severity-critical", "owasp-A08"],
    inserted_at: {:placeholder, :timestamp},
    updated_at: {:placeholder, :timestamp}
  },
  %{
    name: "Weak Random Number Generation",
    description: "Detects use of weak random number generators for security purposes",
    language: "elixir",
    type: "weak_cryptography",
    severity: "medium",
    cwe_id: "CWE-338",
    owasp_category: "A02:2021 - Cryptographic Failures",
    remediation: "Use Elixir\\",
    confidence: "medium",
    framework: nil,
    regex_patterns: [":rand\\.uniform\\s*\\(", "Enum\\.random\\s*\\(", ":random\\.uniform\\s*\\("],
    safe_usage_patterns: [],
    example_code: nil,
    fix_template: nil,
    tier_id: Map.get(tiers, "protected"),
    is_active: true,
    source: "rsolv",
    tags: ["elixir", "severity-medium", "owasp-A02"],
    inserted_at: {:placeholder, :timestamp},
    updated_at: {:placeholder, :timestamp}
  },
  %{
    name: "XML External Entity Injection",
    description: "Detects potential XXE vulnerabilities in XML parsing",
    language: "elixir",
    type: "xml_external_entities",
    severity: "high",
    cwe_id: "CWE-611",
    owasp_category: "A05:2021 - Security Misconfiguration",
    remediation: "Disable external entity processing in Elixir XML parsers. Use SweetXml or other safe Elixir XML parsing libraries with XXE protection enabled by default",
    confidence: "medium",
    framework: nil,
    regex_patterns: [":xmerl_scan\\.string\\s*\\("],
    safe_usage_patterns: [],
    example_code: nil,
    fix_template: nil,
    tier_id: Map.get(tiers, "protected"),
    is_active: true,
    source: "rsolv",
    tags: ["elixir", "severity-high", "owasp-A05"],
    inserted_at: {:placeholder, :timestamp},
    updated_at: {:placeholder, :timestamp}
  },
  %{
    name: "Use of Vulnerable Dependencies",
    description: "Detects potentially vulnerable Elixir/Erlang functions",
    language: "elixir",
    type: "vulnerable_components",
    severity: "medium",
    cwe_id: "CWE-1104",
    owasp_category: "A06:2021 - Vulnerable and Outdated Components",
    remediation: "Use modern Elixir alternatives: System.monotonic_time instead of :erlang.now, :rand instead of :random, and always use safe option with binary_to_term",
    confidence: "medium",
    framework: nil,
    regex_patterns: [":erlang\\.now\\s*\\(\\)", ":random\\."],
    safe_usage_patterns: [],
    example_code: nil,
    fix_template: nil,
    tier_id: Map.get(tiers, "protected"),
    is_active: true,
    source: "rsolv",
    tags: ["elixir", "severity-medium", "owasp-A06"],
    inserted_at: {:placeholder, :timestamp},
    updated_at: {:placeholder, :timestamp}
  },
  %{
    name: "Missing Strong Parameters",
    description: "Rails controllers using params without permit() allowing mass assignment",
    language: "ruby",
    type: "mass_assignment",
    severity: "high",
    cwe_id: "CWE-915",
    owasp_category: "A01:2021 - Broken Access Control",
    remediation: "Use strong parameters with permit(): params.require(:model).permit(:field1, :field2). Never use permit! in production.",
    confidence: "medium",
    framework: nil,
    regex_patterns: ["\\.(create|update|update_attributes|assign_attributes)\\s*\\(\\s*params(?!\\s*\\.\\s*(require|permit))", "User\\.new\\s*\\(\\s*params\\[", "\\.permit!\\s*\\)", "\\.(create!|update!)\\s*\\(\\s*params\\[", "\\.insert_all\\s*\\(\\s*params\\[", "\\.upsert_all\\s*\\(\\s*params\\["],
    safe_usage_patterns: [],
    example_code: nil,
    fix_template: nil,
    tier_id: Map.get(tiers, "protected"),
    is_active: true,
    source: "rsolv",
    tags: ["ruby", "severity-high", "owasp-A01"],
    inserted_at: {:placeholder, :timestamp},
    updated_at: {:placeholder, :timestamp}
  },
  %{
    name: "ERB Template Injection",
    description: "Server-side template injection through ERB evaluation with user input",
    language: "ruby",
    type: "template_injection",
    severity: "critical",
    cwe_id: "CWE-94",
    owasp_category: "A03:2021 - Injection",
    remediation: "Never render user input as Rails ERB templates. Use static Rails templates with safe data binding and Rails helpers.",
    confidence: "medium",
    framework: nil,
    regex_patterns: ["ERB\\.new\\s*\\(\\s*params\\[", "ERB\\.new\\s*\\(\\s*user_template\\)"],
    safe_usage_patterns: [],
    example_code: nil,
    fix_template: nil,
    tier_id: Map.get(tiers, "protected"),
    is_active: true,
    source: "rsolv",
    tags: ["ruby", "severity-critical", "owasp-A03"],
    inserted_at: {:placeholder, :timestamp},
    updated_at: {:placeholder, :timestamp}
  },
  %{
    name: "Unsafe Route Constraints",
    description: "Route constraints that can be bypassed or allow code execution",
    language: "ruby",
    type: "broken_access_control",
    severity: "high",
    cwe_id: "CWE-285",
    owasp_category: "A01:2021 - Broken Access Control",
    remediation: "Use specific, restrictive regex patterns for Rails route constraints. Avoid dynamic constraints with user input in Rails routes.",
    confidence: "medium",
    framework: nil,
    regex_patterns: ["constraints:\\s*\\{\\s*\\w+:\\s*\\", "constraints:\\s*\\{\\s*\\w+:\\s*\\", "constraints:\\s*lambda.*?eval\\s*\\(", "constraints\\s+lambda.*?\\{\\s*\\|\\s*req\\s*\\|\\s*true\\s*\\}", "constraints\\s+subdomain:\\s*\\"],
    safe_usage_patterns: [],
    example_code: nil,
    fix_template: nil,
    tier_id: Map.get(tiers, "protected"),
    is_active: true,
    source: "rsolv",
    tags: ["ruby", "severity-high", "owasp-A01"],
    inserted_at: {:placeholder, :timestamp},
    updated_at: {:placeholder, :timestamp}
  },
  %{
    name: "Insecure Session Configuration",
    description: "Rails session configuration without proper security flags",
    language: "ruby",
    type: "security_misconfiguration",
    severity: "medium",
    cwe_id: "CWE-614",
    owasp_category: "A05:2021 - Security Misconfiguration",
    remediation: "Configure Rails sessions with secure: true, httponly: true, and same_site: :strict for HTTPS environments. Review Rails session store configuration.",
    confidence: "medium",
    framework: nil,
    regex_patterns: ["config\\.session_store.*?secure:\\s*false", "config\\.session_store.*?httponly:\\s*false", "config\\.session_store.*?same_site:\\s*:none", "config\\.session_store\\s*:cookie_store,\\s*key:", "Rails\\.application\\.config\\.session_store\\s*:cookie_store"],
    safe_usage_patterns: [],
    example_code: nil,
    fix_template: nil,
    tier_id: Map.get(tiers, "protected"),
    is_active: true,
    source: "rsolv",
    tags: ["ruby", "severity-medium", "owasp-A05"],
    inserted_at: {:placeholder, :timestamp},
    updated_at: {:placeholder, :timestamp}
  },
  %{
    name: "Dangerous Production Configuration",
    description: "Development settings enabled in production environment",
    language: "ruby",
    type: "debug_mode",
    severity: "medium",
    cwe_id: "CWE-489",
    owasp_category: "A05:2021 - Security Misconfiguration",
    remediation: "Ensure Rails production environment has consider_all_requests_local=false, debug gems removed, and proper Rails caching enabled",
    confidence: "medium",
    framework: nil,
    regex_patterns: ["config\\.consider_all_requests_local\\s*=\\s*true", "config\\.action_controller\\.perform_caching\\s*=\\s*false", "config\\.log_level\\s*=\\s*:debug", "config\\.eager_load\\s*=\\s*false", "config\\.cache_classes\\s*=\\s*false"],
    safe_usage_patterns: [],
    example_code: nil,
    fix_template: nil,
    tier_id: Map.get(tiers, "protected"),
    is_active: true,
    source: "rsolv",
    tags: ["ruby", "severity-medium", "owasp-A05"],
    inserted_at: {:placeholder, :timestamp},
    updated_at: {:placeholder, :timestamp}
  },
  %{
    name: "ActionMailer Injection",
    description: "Email header injection through ActionMailer with unvalidated input",
    language: "ruby",
    type: "template_injection",
    severity: "high",
    cwe_id: "CWE-117",
    owasp_category: "A03:2021 - Injection",
    remediation: "Validate and sanitize email headers. Use address validation for email fields.",
    confidence: "medium",
    framework: nil,
    regex_patterns: ["mail\\s*\\(\\s*to:\\s*params\\["],
    safe_usage_patterns: [],
    example_code: nil,
    fix_template: nil,
    tier_id: Map.get(tiers, "protected"),
    is_active: true,
    source: "rsolv",
    tags: ["ruby", "severity-high", "owasp-A03"],
    inserted_at: {:placeholder, :timestamp},
    updated_at: {:placeholder, :timestamp}
  },
  %{
    name: "CVE-2021-22880 - Open Redirect",
    description: "Host header injection leading to open redirect vulnerability",
    language: "ruby",
    type: "open_redirect",
    severity: "medium",
    cwe_id: "CWE-601",
    owasp_category: "A01:2021 - Broken Access Control",
    remediation: "Validate host headers against an allowlist before using in Rails redirects",
    confidence: "medium",
    framework: nil,
    regex_patterns: ["redirect_to\\s+request\\.protocol\\s*\\+\\s*request\\.host"],
    safe_usage_patterns: [],
    example_code: nil,
    fix_template: nil,
    tier_id: Map.get(tiers, "protected"),
    is_active: true,
    source: "rsolv",
    tags: ["ruby", "severity-medium", "owasp-A01"],
    inserted_at: {:placeholder, :timestamp},
    updated_at: {:placeholder, :timestamp}
  },
  %{
    name: "CVE-2020-8264 - Security Constraint Bypass",
    description: "Bypass of security constraints through skip callback conditions",
    language: "ruby",
    type: "broken_access_control",
    severity: "high",
    cwe_id: "CWE-285",
    owasp_category: "A01:2021 - Broken Access Control",
    remediation: "Never use user input in Rails skip callback conditions. Use safe, predefined conditions in Rails controllers.",
    confidence: "medium",
    framework: nil,
    regex_patterns: ["skip_before_action.*?if:\\s*->\\s*\\{.*?params\\[", "skip_around_action.*?if:\\s*params\\[", "skip_after_action.*?if:\\s*->\\s*\\{.*?eval\\s*\\("],
    safe_usage_patterns: [],
    example_code: nil,
    fix_template: nil,
    tier_id: Map.get(tiers, "protected"),
    is_active: true,
    source: "rsolv",
    tags: ["ruby", "severity-high", "owasp-A01"],
    inserted_at: {:placeholder, :timestamp},
    updated_at: {:placeholder, :timestamp}
  },
  %{
    name: "Django Template XSS",
    description: "Cross-site scripting through unsafe Django template filters",
    language: "python",
    type: "xss",
    severity: "medium",
    cwe_id: "CWE-79",
    owasp_category: "A03:2021 - Injection",
    remediation: "Use Django template automatic escaping or Django escape filter. Only use |safe with trusted, sanitized content in Django templates.",
    confidence: "medium",
    framework: nil,
    regex_patterns: ["\\{\\{\\s*\\w*\\w*content\\w*\\s*\\|\\s*safe\\s*\\}\\}", "\\{\\{\\s*.*?\\.body\\s*\\|\\s*safe\\s*\\}\\}", "mark_safe\\s*\\(\\s*user_\\w+"],
    safe_usage_patterns: [],
    example_code: nil,
    fix_template: nil,
    tier_id: Map.get(tiers, "protected"),
    is_active: true,
    source: "rsolv",
    tags: ["python", "severity-medium", "owasp-A03"],
    inserted_at: {:placeholder, :timestamp},
    updated_at: {:placeholder, :timestamp}
  },
  %{
    name: "Dangerous Django Debug Settings",
    description: "Debug mode and development settings enabled in production",
    language: "python",
    type: "debug_mode",
    severity: "high",
    cwe_id: "CWE-489",
    owasp_category: "A05:2021 - Security Misconfiguration",
    remediation: "Set Django DEBUG=False, configure Django ALLOWED_HOSTS, remove debug apps from Django INSTALLED_APPS, and use Django environment-specific settings",
    confidence: "medium",
    framework: nil,
    regex_patterns: ["DEBUG\\s*=\\s*True"],
    safe_usage_patterns: [],
    example_code: nil,
    fix_template: nil,
    tier_id: Map.get(tiers, "protected"),
    is_active: true,
    source: "rsolv",
    tags: ["python", "severity-high", "owasp-A05"],
    inserted_at: {:placeholder, :timestamp},
    updated_at: {:placeholder, :timestamp}
  },
  %{
    name: "Insecure Django Session Configuration",
    description: "Django session and cookie settings without proper security flags",
    language: "python",
    type: "security_misconfiguration",
    severity: "medium",
    cwe_id: "CWE-614",
    owasp_category: "A05:2021 - Security Misconfiguration",
    remediation: "Set Django session secure=True, httponly=True, and samesite=",
    confidence: "medium",
    framework: nil,
    regex_patterns: ["SESSION_COOKIE_SECURE\\s*=\\s*False", "SESSION_COOKIE_HTTPONLY\\s*=\\s*False", "SESSION_COOKIE_SAMESITE\\s*=\\s*None", "CSRF_COOKIE_SECURE\\s*=\\s*False", "CSRF_COOKIE_HTTPONLY\\s*=\\s*False", "SESSION_EXPIRE_AT_BROWSER_CLOSE\\s*=\\s*False", "SESSION_COOKIE_AGE\\s*=\\s*31536000", "SESSION_SAVE_EVERY_REQUEST\\s*=\\s*False"],
    safe_usage_patterns: [],
    example_code: nil,
    fix_template: nil,
    tier_id: Map.get(tiers, "protected"),
    is_active: true,
    source: "rsolv",
    tags: ["python", "severity-medium", "owasp-A05"],
    inserted_at: {:placeholder, :timestamp},
    updated_at: {:placeholder, :timestamp}
  },
  %{
    name: "Django Broken Authentication",
    description: "Weak authentication patterns and missing validation",
    language: "python",
    type: "broken_authentication",
    severity: "high",
    cwe_id: "CWE-287",
    owasp_category: "A07:2021 - Identification and Authentication Failures",
    remediation: "Use Django built-in authentication system, require Django login decorators, implement Django password validators, avoid hardcoded credentials",
    confidence: "medium",
    framework: nil,
    regex_patterns: ["def\\s+\\w*admin\\w*.*?\\(.*?request.*?\\):(?!.*@login_required)(?!.*request\\.user\\.is_authenticated)"],
    safe_usage_patterns: [],
    example_code: nil,
    fix_template: nil,
    tier_id: Map.get(tiers, "protected"),
    is_active: true,
    source: "rsolv",
    tags: ["python", "severity-high", "owasp-A07"],
    inserted_at: {:placeholder, :timestamp},
    updated_at: {:placeholder, :timestamp}
  },
  %{
    name: "Django CSRF Protection Bypass",
    description: "Cross-Site Request Forgery protection bypassed or disabled",
    language: "python",
    type: "cross_site_request_forgery",
    severity: "high",
    cwe_id: "CWE-352",
    owasp_category: "A01:2021 - Broken Access Control",
    remediation: "Remove Django @csrf_exempt from sensitive views, include Django {% csrf_token %} in forms, send CSRF token in AJAX requests using Django CSRF middleware",
    confidence: "medium",
    framework: nil,
    regex_patterns: ["@csrf_exempt\\s+def\\s+transfer_money", "@csrf_exempt\\s+def\\s+delete_account", "@csrf_exempt\\s+def\\s+change_password"],
    safe_usage_patterns: [],
    example_code: nil,
    fix_template: nil,
    tier_id: Map.get(tiers, "protected"),
    is_active: true,
    source: "rsolv",
    tags: ["python", "severity-high", "owasp-A01"],
    inserted_at: {:placeholder, :timestamp},
    updated_at: {:placeholder, :timestamp}
  },
  %{
    name: "Django Clickjacking Vulnerability",
    description: "Missing or disabled X-Frame-Options protection",
    language: "python",
    type: "security_misconfiguration",
    severity: "medium",
    cwe_id: "CWE-1021",
    owasp_category: "A05:2021 - Security Misconfiguration",
    remediation: "Use Django X_FRAME_OPTIONS = ",
    confidence: "medium",
    framework: nil,
    regex_patterns: ["@xframe_options_exempt"],
    safe_usage_patterns: [],
    example_code: nil,
    fix_template: nil,
    tier_id: Map.get(tiers, "protected"),
    is_active: true,
    source: "rsolv",
    tags: ["python", "severity-medium", "owasp-A05"],
    inserted_at: {:placeholder, :timestamp},
    updated_at: {:placeholder, :timestamp}
  },
  %{
    name: "Django Mass Assignment",
    description: "Mass assignment vulnerabilities in Django model operations",
    language: "python",
    type: "mass_assignment",
    severity: "high",
    cwe_id: "CWE-915",
    owasp_category: "A01:2021 - Broken Access Control",
    remediation: "Use ModelForm with explicit fields, validate input, implement field whitelisting",
    confidence: "medium",
    framework: nil,
    regex_patterns: ["User\\.objects\\.create\\s*\\(\\s*\\*\\*\\s*request\\.POST\\s*\\)", "User\\s*\\(\\s*\\*\\*\\s*request\\.POST\\.dict\\(\\)\\s*\\)\\.save\\(\\)", "User\\.objects\\.bulk_create\\s*\\(\\s*\\[\\s*User\\s*\\(\\s*\\*\\*\\s*data\\s*\\)", "User\\.objects\\.filter\\s*\\(.*?\\)\\.update\\s*\\(\\s*\\*\\*\\s*request\\.POST\\s*\\)", "user\\.__dict__\\.update\\s*\\(\\s*request\\.POST\\s*\\)", "form\\s*=\\s*ModelForm\\s*\\(\\s*request\\.POST.*?instance\\s*=\\s*user\\s*\\)", "class\\s+\\w+Form\\s*\\(\\s*ModelForm\\s*\\):.*?class\\s+Meta:.*?model\\s*=\\s*\\w+(?!.*fields)"],
    safe_usage_patterns: [],
    example_code: nil,
    fix_template: nil,
    tier_id: Map.get(tiers, "protected"),
    is_active: true,
    source: "rsolv",
    tags: ["python", "severity-high", "owasp-A01"],
    inserted_at: {:placeholder, :timestamp},
    updated_at: {:placeholder, :timestamp}
  },
  %{
    name: "CVE-2021-33571 - URL Validation Bypass",
    description: "URL validation bypass allowing open redirects",
    language: "python",
    type: "open_redirect",
    severity: "medium",
    cwe_id: "CWE-601",
    owasp_category: "A01:2021 - Broken Access Control",
    remediation: "Validate redirect URLs against allowlist, sanitize URL schemes, use Django is_safe_url() for redirects",
    confidence: "medium",
    framework: nil,
    regex_patterns: ["URLValidator\\(\\)\\s*\\(\\s*user_\\w+"],
    safe_usage_patterns: [],
    example_code: nil,
    fix_template: nil,
    tier_id: Map.get(tiers, "protected"),
    is_active: true,
    source: "rsolv",
    tags: ["python", "severity-medium", "owasp-A01"],
    inserted_at: {:placeholder, :timestamp},
    updated_at: {:placeholder, :timestamp}
  }
]

{count, _} = Repo.insert_all(SecurityPattern, patterns, placeholders: %{timestamp: NaiveDateTime.utc_now() |> NaiveDateTime.truncate(:second)})

IO.puts("✅ Successfully loaded #{count} security patterns!")

# Print summary by language
IO.puts("\n📊 Patterns by language:")
IO.puts("  ruby: 21")
IO.puts("  python: 8")
IO.puts("  elixir: 6")
IO.puts("  javascript: 3")
IO.puts("  typescript: 1")