
# RSOLV Configuration for Dogfooding
# This configuration is used when RSOLV runs on itself

# Issue processing settings
issues:
  # Labels that indicate an issue should be processed
  automation_labels:
    - "rsolv:automate"
    - "good first issue"
    - "bug"
  
  # Labels to exclude from processing
  exclude_labels:
    - "wontfix"
    - "duplicate"
    - "in-progress"

# AI settings
ai:
  # Provider preferences (in order)
  providers:
    - anthropic
    - openrouter
    - ollama
  
  # Context settings
  max_context_files: 10
  include_test_files: true
  
# Security settings
security:
  # Enable security analysis
  enable_analysis: true
  
  # Security patterns to check
  patterns:
    - xss
    - sql-injection
    - path-traversal
    - command-injection
    - authentication
    - authorization

# PR settings
pull_requests:
  # PR title prefix
  title_prefix: "[RSOLV]"
  
  # Add these labels to generated PRs
  labels:
    - "automated"
    - "rsolv-generated"
  
  # PR description template
  description_template: |
    ## Summary
    This PR was automatically generated by RSOLV to address issue #{{ issue_number }}.
    
    ## Changes
    {{ changes_summary }}
    
    ## Security Analysis
    {{ security_analysis }}
    
    ## Testing
    {{ testing_notes }}
    
    ---
    *Generated by [RSOLV](https://rsolv.dev) - Security-First Issue Automation*

# Repository-specific settings
repository:
  # File patterns to analyze
  include_patterns:
    - "src/**/*.ts"
    - "src/**/*.js"
    - "test/**/*.ts"
    - "*.json"
    - "*.yml"
    - "*.yaml"
  
  # File patterns to exclude
  exclude_patterns:
    - "node_modules/**"
    - "dist/**"
    - "coverage/**"
    - "*.lock"