name: 'RSOLV Issue Automation'
description: 'Automates fixing issues in your repository using AI'
author: 'RSOLV Team'
branding:
  icon: 'zap'
  color: 'purple'
inputs:
  api_key:
    description: 'RSOLV API key for authentication (deprecated, use rsolvApiKey)'
    required: false
  rsolvApiKey:
    description: 'RSOLV API key for platform authentication and phase data persistence'
    required: false
  config_path:
    description: 'Path to RSOLV configuration file'
    required: false
    default: '.github/rsolv.yml'
  issue_label:
    description: 'Label to identify issues for automation'
    required: false
    default: 'rsolv:automate'
  environment_variables:
    description: 'JSON string of environment variables to pass to the container'
    required: false
  api_url:
    description: 'RSOLV API URL (defaults to production)'
    required: false
    default: 'https://api.rsolv.dev'
  jira_host:
    description: 'Jira instance hostname (e.g., your-domain.atlassian.net)'
    required: false
  jira_email:
    description: 'Jira account email for API authentication'
    required: false
  jira_api_token:
    description: 'Jira API token for authentication'
    required: false
  jira_autofix_label:
    description: 'Label to identify Jira issues for automation'
    required: false
    default: 'autofix'
  jira_rsolv_label:
    description: 'Alternative label to identify Jira issues for automation'
    required: false
    default: 'rsolv'
  jira_jql:
    description: 'Custom JQL query to find issues (overrides label-based search)'
    required: false
  mode:
    description: 'Operation mode: scan, validate, mitigate, or full (all phases)'
    required: false
    default: 'full'
  scan_mode:
    description: 'Scan mode operation: fix (default) or scan'
    required: false
    default: 'fix'
  enable_security_analysis:
    description: 'Enable security vulnerability analysis'
    required: false
    default: 'true'
  max_issues:
    description: 'Maximum number of issues to process in a single run'
    required: false
    default: '1'
  issue_number:
    description: 'Specific issue number to process (for workflow_dispatch)'
    required: false
    default: ''
  use_git_based_editing:
    description: 'Enable git-based in-place editing for true file modifications (ADR-012)'
    required: false
    default: 'true'
  enable_enhanced_context:
    description: 'Enable enhanced context gathering (uses more tokens but may improve accuracy)'
    required: false
    default: 'true'  # Changed to true for better analysis
  enable_ast_validation:
    description: 'Enable AST-based validation to reduce false positives (recommended)'
    required: false
    default: 'true'
  use_structured_phases:
    description: 'Enable structured phased prompting to ensure files are edited before JSON generation'
    required: false
    default: 'true'
  enable_educational_pr:
    description: 'Enable educational PR descriptions with security explanations'
    required: false
    default: 'true'
runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    RSOLV_API_KEY: ${{ inputs.api_key }}
    RSOLV_API_URL: ${{ inputs.api_url }}
    RSOLV_CONFIG_PATH: ${{ inputs.config_path }}
    RSOLV_ISSUE_LABEL: ${{ inputs.issue_label }}
    RSOLV_ENVIRONMENT_VARIABLES: ${{ inputs.environment_variables }}
    # GITHUB_TOKEN should be passed from the workflow env
    JIRA_HOST: ${{ inputs.jira_host }}
    JIRA_EMAIL: ${{ inputs.jira_email }}
    JIRA_API_TOKEN: ${{ inputs.jira_api_token }}
    JIRA_AUTOFIX_LABEL: ${{ inputs.jira_autofix_label }}
    JIRA_RSOLV_LABEL: ${{ inputs.jira_rsolv_label }}
    JIRA_JQL: ${{ inputs.jira_jql }}
    RSOLV_MODE: ${{ inputs.mode }}
    RSOLV_SCAN_MODE: ${{ inputs.scan_mode }}
    RSOLV_ENABLE_SECURITY_ANALYSIS: ${{ inputs.enable_security_analysis }}
    RSOLV_MAX_ISSUES: ${{ inputs.max_issues }}
    RSOLV_ISSUE_NUMBER: ${{ inputs.issue_number }}
    RSOLV_USE_GIT_BASED_EDITING: ${{ inputs.use_git_based_editing }}
    RSOLV_ENABLE_ENHANCED_CONTEXT: ${{ inputs.enable_enhanced_context }}
    RSOLV_ENABLE_AST_VALIDATION: ${{ inputs.enable_ast_validation }}
    RSOLV_USE_STRUCTURED_PHASES: ${{ inputs.use_structured_phases }}
    RSOLV_EDUCATIONAL_PR: ${{ inputs.enable_educational_pr }}
outputs:
  has_issues:
    description: 'Whether issues were found for processing'
  security_findings:
    description: 'Security vulnerabilities found in JSON format'
  educational_content:
    description: 'Educational explanation of the issues and fixes'
  issue_analysis:
    description: 'Full analysis of the issues in JSON format'
  scan_results:
    description: 'Results from vulnerability scan in JSON format'
  created_issues:
    description: 'GitHub issues created from scan results'