name: 'RSOLV Issue Automation'
description: 'Automates fixing issues in your repository using AI'
author: 'RSOLV Team'
branding:
  icon: 'zap'
  color: 'purple'
inputs:
  api_key:
    description: 'RSOLV API key for authentication'
    required: true
  config_path:
    description: 'Path to RSOLV configuration file'
    required: false
    default: '.github/rsolv.yml'
  issue_label:
    description: 'Label to identify issues for automation'
    required: false
    default: 'rsolv:automate'
  environment_variables:
    description: 'JSON string of environment variables to pass to the container'
    required: false
  api_url:
    description: 'RSOLV API URL (defaults to production)'
    required: false
    default: 'https://api.rsolv.ai'
  jira_host:
    description: 'Jira instance hostname (e.g., your-domain.atlassian.net)'
    required: false
  jira_email:
    description: 'Jira account email for API authentication'
    required: false
  jira_api_token:
    description: 'Jira API token for authentication'
    required: false
  jira_autofix_label:
    description: 'Label to identify Jira issues for automation'
    required: false
    default: 'autofix'
  jira_rsolv_label:
    description: 'Alternative label to identify Jira issues for automation'
    required: false
    default: 'rsolv'
  jira_jql:
    description: 'Custom JQL query to find issues (overrides label-based search)'
    required: false
  mode:
    description: 'Operation mode: full (default) or analyze-only'
    required: false
    default: 'full'
  enable_security_analysis:
    description: 'Enable security vulnerability analysis'
    required: false
    default: 'true'
runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    RSOLV_API_KEY: ${{ inputs.api_key }}
    RSOLV_API_URL: ${{ inputs.api_url }}
    RSOLV_CONFIG_PATH: ${{ inputs.config_path }}
    RSOLV_ISSUE_LABEL: ${{ inputs.issue_label }}
    RSOLV_ENVIRONMENT_VARIABLES: ${{ inputs.environment_variables }}
    # GITHUB_TOKEN should be passed from the workflow env
    JIRA_HOST: ${{ inputs.jira_host }}
    JIRA_EMAIL: ${{ inputs.jira_email }}
    JIRA_API_TOKEN: ${{ inputs.jira_api_token }}
    JIRA_AUTOFIX_LABEL: ${{ inputs.jira_autofix_label }}
    JIRA_RSOLV_LABEL: ${{ inputs.jira_rsolv_label }}
    JIRA_JQL: ${{ inputs.jira_jql }}
    RSOLV_MODE: ${{ inputs.mode }}
    RSOLV_ENABLE_SECURITY_ANALYSIS: ${{ inputs.enable_security_analysis }}
outputs:
  has_issues:
    description: 'Whether issues were found for processing'
  security_findings:
    description: 'Security vulnerabilities found in JSON format'
  educational_content:
    description: 'Educational explanation of the issues and fixes'
  issue_analysis:
    description: 'Full analysis of the issues in JSON format'