name: 'RSOLV Automated Fix Generator'
description: 'Automatically addresses tagged issues with AI-powered fixes'
author: 'RSOLV'

inputs:
  api_key:
    description: 'API key for RSOLV service'
    required: true
  issue_tag:
    description: 'Tag to identify issues for automation'
    required: false
    default: 'AUTOFIX'
  expert_review_command:
    description: 'Command to request expert review'
    required: false
    default: '/request-expert-review'
  ai_provider:
    description: 'AI provider to use (anthropic, openrouter, mistral, ollama)'
    required: false
    default: 'anthropic'
  anthropic_api_key:
    description: 'API key for Anthropic Claude AI'
    required: false
  openai_api_key:
    description: 'API key for OpenAI'
    required: false
  use_claude_code:
    description: 'Use Claude Code CLI for enhanced context gathering'
    required: false
    default: 'false'
  debug:
    description: 'Enable debug mode'
    required: false
    default: 'false'
  skip_security_check:
    description: 'Skip security checks (not recommended)'
    required: false
    default: 'false'

runs:
  using: 'docker'
  image: 'Dockerfile'

branding:
  icon: 'zap'
  color: 'blue'