name: RSOLV Security Scan

on:
  workflow_dispatch:
  push:
    branches: [ main ]

permissions:
  contents: read
  issues: write

jobs:
  security-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Run RSOLV Security Scan
        uses: RSOLV-dev/rsolv-action@v3.1.0
        with:
          api_key: ${{ secrets.RSOLV_API_KEY }}
          scan_mode: scan
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Display scan results
        if: always()
        run: |
          echo "=== Security Scan Complete ==="
          echo "Check the Issues tab for vulnerabilities found"