name: RSOLV Security Scan Demo

on:
  workflow_dispatch:
    inputs:
      repository:
        description: 'Repository to scan (owner/name)'
        required: false
        default: 'OWASP/NodeGoat'
      
jobs:
  security-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Run RSOLV Security Scan
        uses: ./
        with:
          api_key: ${{ secrets.RSOLV_API_KEY }}
          scan_mode: scan
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Display scan results
        if: always()
        run: |
          echo "Scan completed!"
          echo "Results: ${{ steps.scan.outputs.scan_results }}"
          echo "Created issues: ${{ steps.scan.outputs.created_issues }}"
          
  # After scanning and creating issues, run fix mode
  security-fix:
    runs-on: ubuntu-latest
    needs: security-scan
    if: success()
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Run RSOLV Fix Mode
        uses: ./
        with:
          api_key: ${{ secrets.RSOLV_API_KEY }}
          scan_mode: fix
          issue_label: 'rsolv:automate'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Display fix results
        if: always()
        run: |
          echo "Fix process completed!"
          echo "Check created pull requests for security fixes"