name: RSOLV Fix Issues

on:
  issues:
    types: [opened, labeled]
  workflow_dispatch:
    inputs:
      issue_number:
        description: 'Specific issue number to process (optional)'
        required: false
        type: string

permissions:
  contents: write
  issues: write  
  pull-requests: write

jobs:
  fix-vulnerabilities:
    runs-on: ubuntu-latest
    if: contains(github.event.issue.labels.*.name, 'rsolv:automate') || github.event_name == 'workflow_dispatch'
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Run RSOLV Action - MITIGATE Phase Only
        uses: RSOLV-dev/rsolv-action@main
        with:
          api_key: ${{ secrets.RSOLV_API_KEY }}
          mode: 'mitigate'  # CRITICAL: Only run the fix phase
          issue_number: ${{ github.event.issue.number || inputs.issue_number }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}