apiVersion: apps/v1
kind: Deployment
metadata:
  name: rsolv-platform
  namespace: rsolv-production
spec:
  template:
    spec:
      containers:
      - name: rsolv-platform
        env:
        # Add AI provider API keys for credential vending
        - name: ANTHROPIC_API_KEY
          valueFrom:
            secretKeyRef:
              name: rsolv-secrets
              key: anthropic-api-key
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: rsolv-secrets
              key: openai-api-key
        - name: OPENROUTER_API_KEY
          valueFrom:
            secretKeyRef:
              name: rsolv-secrets
              key: openrouter-api-key