#!/bin/bash

# Test with a PR without issue reference
PAYLOAD='{
  "action": "opened",
  "pull_request": {
    "id": 1,
    "number": 456,
    "title": "[RSOLV] Performance improvements and refactoring",
    "html_url": "https://github.com/test/repo/pull/456",
    "state": "open",
    "merged": false,
    "user": {
      "login": "rsolv-bot"
    },
    "head": {
      "ref": "rsolv/perf-improvements",
      "sha": "def456"
    },
    "base": {
      "repo": {
        "owner": {
          "login": "test-org"
        },
        "name": "test-repo"
      }
    },
    "labels": [
      {"name": "rsolv:automated"},
      {"name": "performance"}
    ],
    "body": "This PR improves application performance by optimizing database queries and refactoring inefficient code.\\n\\nGenerated by RSOLV"
  },
  "repository": {
    "full_name": "test-org/test-repo"
  }
}'

# Remove newlines and extra spaces
PAYLOAD=$(echo "$PAYLOAD" | tr -d '\n' | sed 's/  */ /g')

SECRET='iXs+0T2bElP1sd5rUo/qGQKbg6xkf0sLQt/LOEY/254='

# Compute signature exactly as GitHub does
SIGNATURE=$(echo -n "$PAYLOAD" | openssl dgst -sha256 -hmac "$SECRET" -binary | xxd -p | tr -d '\n')

echo "Testing webhook with PR without issue reference..."
echo "Signature: sha256=$SIGNATURE"
echo ""

curl -i -X POST https://api.rsolv.dev/webhook/github \
  -H "Content-Type: application/json" \
  -H "X-GitHub-Event: pull_request" \
  -H "X-Hub-Signature-256: sha256=$SIGNATURE" \
  -d "$PAYLOAD"