#!/bin/bash
# Test RSOLV GitHub Action locally

set -e

# Colors
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m'

echo -e "${BLUE}=== RSOLV GitHub Action Local Test ===${NC}"
echo -e "${BLUE}Simulating GitHub Action workflow execution${NC}\n"

# Check if RSOLV-action exists
RSOLV_ACTION_PATH="/home/dylan/dev/rsolv/RSOLV-action"

if [ -d "$RSOLV_ACTION_PATH" ]; then
    echo -e "${GREEN}✓ RSOLV-action repository found${NC}"
    
    # Check action.yml
    if [ -f "$RSOLV_ACTION_PATH/action.yml" ]; then
        echo -e "${GREEN}✓ action.yml exists${NC}"
        echo -e "\n${BLUE}Action inputs:${NC}"
        grep -A 20 "inputs:" "$RSOLV_ACTION_PATH/action.yml" | grep -E "^\s+(mode|api_key|github_token|create_issues):" | head -10
    fi
    
    # Check for main script
    if [ -f "$RSOLV_ACTION_PATH/src/index.ts" ] || [ -f "$RSOLV_ACTION_PATH/index.js" ]; then
        echo -e "\n${GREEN}✓ Action implementation found${NC}"
    fi
else
    echo -e "${RED}✗ RSOLV-action not found at $RSOLV_ACTION_PATH${NC}"
    echo -e "${YELLOW}The GitHub Action is in a separate repository${NC}"
fi

echo -e "\n${BLUE}=== Simulated GitHub Action Execution ===${NC}"
echo -e "\n${YELLOW}Step 1: Environment Setup${NC}"
echo "- Repository: test-vulnerable-app"
echo "- Trigger: Issue labeled with 'security'"
echo "- Mode: scan"

echo -e "\n${YELLOW}Step 2: RSOLV Scan Execution${NC}"
echo "The action would:"
echo "1. Clone the repository"
echo "2. Detect languages (JavaScript found)"
echo "3. Call RSOLV API to get patterns"
echo "4. Scan all .js files for vulnerabilities"
echo "5. Create GitHub issues for findings"

echo -e "\n${YELLOW}Step 3: Issue Creation${NC}"
echo "For each vulnerability found, the action creates an issue with:"
echo -e "\n${BLUE}Example Issue:${NC}"
cat << 'EOF'
Title: 🔴 [SECURITY] SQL Injection in /api/users/:id endpoint

## Vulnerability Details

**Type**: SQL Injection
**Severity**: CRITICAL
**File**: server.js
**Line**: 25
**CWE**: CWE-89
**OWASP**: A03:2021 – Injection

## Description

User input is directly concatenated into an SQL query without proper sanitization or parameterization. This allows attackers to inject malicious SQL code.

## Vulnerable Code

```javascript
const query = "SELECT * FROM users WHERE id = '" + userId + "'";
db.query(query, (err, results) => {
  // ...
});
```

## Recommended Fix

Use parameterized queries to prevent SQL injection:

```javascript
const query = "SELECT * FROM users WHERE id = ?";
db.query(query, [userId], (err, results) => {
  // ...
});
```

## Impact

An attacker could:
- Extract sensitive data from the database
- Modify or delete data
- Execute administrative operations
- Potentially gain server access

## References

- [OWASP SQL Injection](https://owasp.org/www-community/attacks/SQL_Injection)
- [CWE-89: SQL Injection](https://cwe.mitre.org/data/definitions/89.html)

---
*This issue was automatically created by RSOLV. Add the `rsolv-fix` label to generate an automated fix.*
EOF

echo -e "\n${YELLOW}Step 4: Auto-Fix Mode${NC}"
echo "When 'rsolv-fix' label is added:"
echo "1. RSOLV analyzes the issue context"
echo "2. Generates secure fix using AI"
echo "3. Creates a branch: 'rsolv-fix-issue-1'"
echo "4. Commits the fix with detailed message"
echo "5. Opens a pull request"

echo -e "\n${BLUE}Example Pull Request:${NC}"
cat << 'EOF'
Title: Fix SQL Injection vulnerability in /api/users/:id endpoint

## Summary

This PR fixes a critical SQL injection vulnerability by implementing parameterized queries.

## Changes

- Replace string concatenation with parameterized query
- Add input validation
- Update error handling

## Testing

- [x] Verified original functionality works
- [x] Tested with malicious input - injection prevented
- [x] Added unit tests for the endpoint

## Security Impact

This fix prevents SQL injection attacks that could lead to:
- Unauthorized data access
- Data manipulation
- Potential system compromise

## Checklist

- [x] Code follows security best practices
- [x] No new vulnerabilities introduced
- [x] Tests pass
- [x] Documentation updated

---
*This PR was automatically generated by RSOLV to fix issue #1*
EOF

echo -e "\n${GREEN}=== Action Workflow Summary ===${NC}"
echo -e "${GREEN}✓ Repository scanned automatically${NC}"
echo -e "${GREEN}✓ 10 vulnerabilities detected and reported${NC}"
echo -e "${GREEN}✓ Issues created with detailed information${NC}"
echo -e "${GREEN}✓ Fixes available on-demand via labeling${NC}"
echo -e "${GREEN}✓ Pull requests include tests and documentation${NC}"

echo -e "\n${BLUE}Benefits:${NC}"
echo "- Continuous security monitoring"
echo "- Automated vulnerability detection"
echo "- One-click fix generation"
echo "- Educational content for developers"
echo "- Pay only for merged fixes"

echo -e "\n${GREEN}Test complete!${NC}"