name: RSOLV Security Scan

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 1'  # Weekly on Monday
  push:
    branches: [ main ]
    paths:
      - '**/*.js'
      - '**/*.ts'
      - '**/*.py'
      - '**/*.rb'

permissions:
  contents: read
  issues: write

jobs:
  security-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: RSOLV Scan - Detect Vulnerabilities
        uses: RSOLV-dev/rsolv-action@v3.1.1
        with:
          api_key: ${{ secrets.RSOLV_API_KEY }}
          mode: 'scan'  # Only run scan phase
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Scan Summary
        if: always()
        run: |
          echo "✅ Security scan complete"
          echo "Check the Issues tab for vulnerabilities with 'rsolv:detected' label"