defmodule RsolvApi.Webhooks.Handlers.GitHubHandlerTest do
  use RsolvApi.DataCase, async: true

  alias RsolvApi.Webhooks.Handlers.GitHubHandler
  alias RsolvApi.Billing.FixAttempt
  alias RsolvApi.Repo

  describe "handle_event/2" do
    test "creates fix attempt on pull request opened" do
      payload = %{
        "action" => "opened",
        "pull_request" => %{
          "id" => 12345,
          "number" => 42,
          "title" => "Fix SQL injection vulnerability",
          "body" => "Fixes issue #10\n\nGenerated by RSOLV",
          "base" => %{
            "repo" => %{
              "name" => "test-repo",
              "owner" => %{"login" => "test-org"}
            }
          },
          "head" => %{"sha" => "abc123"}
        },
        "repository" => %{
          "name" => "test-repo",
          "owner" => %{"login" => "test-org"}
        }
      }

      assert {:ok, :pr_opened} = GitHubHandler.handle_event("pull_request", payload)
      
      # Verify fix attempt was created
      fix_attempt = Repo.get_by(FixAttempt, pr_number: 42, github_org: "test-org")
      assert fix_attempt != nil
      assert fix_attempt.status == "pending"
      assert fix_attempt.repo_name == "test-repo"
      assert fix_attempt.issue_number == 10
    end

    test "updates fix attempt to merged on pull request merged" do
      # First create a pending fix attempt
      {:ok, fix_attempt} = %FixAttempt{}
        |> FixAttempt.changeset(%{
          github_org: "test-org",
          repo_name: "test-repo",
          issue_number: 10,
          pr_number: 42,
          status: "pending"
        })
        |> Repo.insert()

      payload = %{
        "action" => "closed",
        "pull_request" => %{
          "number" => 42,
          "merged" => true,
          "merged_at" => "2025-06-03T10:00:00Z",
          "base" => %{
            "repo" => %{
              "name" => "test-repo",
              "owner" => %{"login" => "test-org"}
            }
          }
        }
      }

      assert {:ok, :merged} = GitHubHandler.handle_event("pull_request", payload)
      
      # Verify status was updated
      updated = Repo.get(FixAttempt, fix_attempt.id)
      assert updated.status == "merged"
      assert updated.merged_at != nil
    end

    test "updates fix attempt to rejected on pull request closed without merge" do
      # First create a pending fix attempt
      {:ok, fix_attempt} = %FixAttempt{}
        |> FixAttempt.changeset(%{
          github_org: "test-org",
          repo_name: "test-repo",
          issue_number: 10,
          pr_number: 42,
          status: "pending"
        })
        |> Repo.insert()

      payload = %{
        "action" => "closed",
        "pull_request" => %{
          "number" => 42,
          "merged" => false,
          "base" => %{
            "repo" => %{
              "name" => "test-repo",
              "owner" => %{"login" => "test-org"}
            }
          }
        }
      }

      assert {:ok, :rejected} = GitHubHandler.handle_event("pull_request", payload)
      
      # Verify status was updated
      updated = Repo.get(FixAttempt, fix_attempt.id)
      assert updated.status == "rejected"
      assert updated.rejected_at != nil
    end

    test "extracts issue number from PR body" do
      pr_body = """
      This PR fixes the security vulnerability identified in issue #123.
      
      Fixes #123
      
      Generated by RSOLV
      """

      assert 123 = GitHubHandler.extract_issue_number(pr_body)
    end

    test "returns nil when no issue number in PR body" do
      pr_body = "This PR does some general improvements"
      assert nil == GitHubHandler.extract_issue_number(pr_body)
    end

    test "ignores non-RSOLV pull requests" do
      payload = %{
        "action" => "opened",
        "pull_request" => %{
          "number" => 42,
          "body" => "Regular PR without RSOLV mention",
          "base" => %{
            "repo" => %{
              "name" => "test-repo",
              "owner" => %{"login" => "test-org"}
            }
          }
        }
      }

      assert {:ok, :ignored} = GitHubHandler.handle_event("pull_request", payload)
      
      # Verify no fix attempt was created
      fix_attempt = Repo.get_by(FixAttempt, pr_number: 42)
      assert fix_attempt == nil
    end

    test "handles issue closed event" do
      payload = %{
        "action" => "closed",
        "issue" => %{
          "number" => 10,
          "state" => "closed"
        },
        "repository" => %{
          "name" => "test-repo",
          "owner" => %{"login" => "test-org"}
        }
      }

      assert {:ok, :issue_closed} = GitHubHandler.handle_event("issues", payload)
    end
  end
end