/**
 * GitHub Actions Job Summary — renders pipeline results as a markdown
 * summary visible in the Actions workflow run page.
 *
 * Uses $GITHUB_STEP_SUMMARY to write markdown that GitHub renders
 * inline in the workflow run UI — immediately visible without navigating
 * to issues or PRs.
 */

import { appendFileSync } from 'fs';
import { logger } from './logger.js';

interface ScanIssue {
  number: number;
  title?: string;
  cwe_id?: string;
  vulnerabilityType?: string;
}

interface ProcessResult {
  success: boolean;
  phase: string;
  data?: Record<string, unknown>;
  error?: string;
}

/**
 * Write a job summary for a SCAN phase result.
 */
export function writeScanSummary(
  repoFullName: string,
  createdIssues: ScanIssue[],
  vulnerabilityCount: number
): void {
  const summaryFile = process.env.GITHUB_STEP_SUMMARY;
  if (!summaryFile) return;

  const lines: string[] = [
    `## 🔒 RSOLV Security Scan — ${repoFullName}`,
    '',
  ];

  if (createdIssues.length === 0) {
    lines.push('✅ No vulnerabilities detected.');
  } else {
    lines.push(`Found **${vulnerabilityCount}** potential vulnerabilities. Created **${createdIssues.length}** issues for validation.`);
    lines.push('');
    lines.push('| Issue | Type |');
    lines.push('|-------|------|');

    for (const issue of createdIssues) {
      const cwe = issue.cwe_id || issue.vulnerabilityType || 'Unknown';
      const title = issue.title || `#${issue.number}`;
      lines.push(`| [#${issue.number}](../../issues/${issue.number}) | ${cwe} |`);
    }

    lines.push('');
    lines.push('Each issue will now be validated through behavioral testing.');
  }

  lines.push('');
  lines.push('---');
  lines.push('*Generated by [RSOLV](https://rsolv.dev) — AI-powered security vulnerability remediation*');

  try {
    appendFileSync(summaryFile, lines.join('\n') + '\n');
    logger.info('[JobSummary] Scan summary written');
  } catch (error) {
    logger.warn('[JobSummary] Failed to write scan summary', error);
  }
}

/**
 * Write a job summary for a PROCESS (validate+mitigate) phase result.
 */
export function writeProcessSummary(
  repoFullName: string,
  issueNumber: number,
  result: ProcessResult
): void {
  const summaryFile = process.env.GITHUB_STEP_SUMMARY;
  if (!summaryFile) return;

  const lines: string[] = [
    `## 🔒 RSOLV Validation — ${repoFullName} #${issueNumber}`,
    '',
  ];

  if (!result.success) {
    lines.push(`❌ Validation failed: ${result.error || 'Unknown error'}`);
  } else {
    const data = (result.data || {}) as Record<string, unknown>;
    const classification = extractClassification(data);
    const prUrl = extractPrUrl(data);

    switch (classification) {
      case 'validated':
        if (prUrl) {
          lines.push(`✅ **Vulnerability confirmed** — behavioral test proves the vulnerability exists.`);
          lines.push('');
          lines.push(`🔧 **Fix PR created:** [${prUrl}](${prUrl})`);
        } else {
          lines.push(`✅ **Vulnerability confirmed** — behavioral test proves the vulnerability exists.`);
          lines.push('');
          lines.push('Fix generation in progress.');
        }
        break;

      case 'false_positive_defense_confirmed':
        lines.push(`🛡️ **Defense confirmed** — behavioral test PASSED, proving the security defense works.`);
        lines.push('');
        lines.push('No action needed. The flagged code is properly defended.');
        break;

      case 'false_positive_counter_indicated':
        lines.push(`🛡️ **False positive** — counter-indicator analysis found the vulnerability is not exploitable.`);
        lines.push('');
        lines.push('No action needed.');
        break;

      case 'false_positive':
        lines.push(`⚪ **Not validated** — could not prove the vulnerability through behavioral testing.`);
        break;

      case 'infrastructure_failure':
        lines.push(`⚠️ **Infrastructure issue** — test environment setup failed. This is not a code problem.`);
        break;

      case 'max_turns_exceeded':
        lines.push(`⏱️ **Timed out** — validation exceeded the turn limit. The vulnerability may be real but complex to test.`);
        break;

      default:
        lines.push(`Validation complete: ${classification || 'unknown'}`);
    }
  }

  lines.push('');
  lines.push('---');
  lines.push('*Generated by [RSOLV](https://rsolv.dev) — AI-powered security vulnerability remediation*');

  try {
    appendFileSync(summaryFile, lines.join('\n') + '\n');
    logger.info(`[JobSummary] Process summary written for #${issueNumber}`);
  } catch (error) {
    logger.warn('[JobSummary] Failed to write process summary', error);
  }
}

function extractClassification(data: Record<string, unknown>): string | undefined {
  // Classification may be nested under validate or at top level
  if (data.classification) return String(data.classification);
  const validate = data.validate as Record<string, unknown> | undefined;
  if (validate?.classification) return String(validate.classification);
  return undefined;
}

function extractPrUrl(data: Record<string, unknown>): string | undefined {
  if (data.pr_url) return String(data.pr_url);
  const mitigate = data.mitigate as Record<string, unknown> | undefined;
  if (mitigate?.pr_url) return String(mitigate.pr_url);
  return undefined;
}
