/**
 * GitHub Actions Job Summary — renders pipeline results as a markdown
 * summary visible in the Actions workflow run page.
 *
 * Uses $GITHUB_STEP_SUMMARY to write markdown that GitHub renders
 * inline in the workflow run UI — immediately visible without navigating
 * to issues or PRs.
 */

import { appendFileSync } from 'fs';
import { logger } from './logger.js';
import type { ScanPlanResponse } from '../scanner/types.js';

interface ScanIssue {
  number: number;
  title?: string;
  cwe_id?: string;
  vulnerabilityType?: string;
}

interface ProcessResult {
  success: boolean;
  phase: string;
  data?: Record<string, unknown>;
  error?: string;
}

/**
 * Write a job summary for a SCAN phase result.
 * When a scan plan is available, includes budget info and selected/deferred breakdown.
 */
export function writeScanSummary(
  repoFullName: string,
  createdIssues: ScanIssue[],
  vulnerabilityCount: number,
  scanPlan?: ScanPlanResponse | null
): void {
  const summaryFile = process.env.GITHUB_STEP_SUMMARY;
  if (!summaryFile) return;

  const lines: string[] = [
    `## 🔒 RSOLV Security Scan — ${repoFullName}`,
    '',
  ];

  if (vulnerabilityCount === 0) {
    lines.push('✅ No vulnerabilities detected.');
  } else if (scanPlan) {
    // Budget-aware summary
    const budget = scanPlan.budget;
    const tierLabel = capitalize(budget.tier);
    const selectedCount = scanPlan.selected.length;
    const deferredCount = scanPlan.deferred.length;

    lines.push(`Found **${vulnerabilityCount}** potential vulnerabilities.`);
    lines.push('');

    // Budget line
    const budgetParts: string[] = [`${budget.validate_used}/${budget.validate_limit} included used`];
    if (budget.overage_cap_cents > 0) {
      budgetParts.push(`$${budget.overage_cap_cents / 100} overage cap`);
    }
    lines.push(`**Budget:** ${budgetParts.join(' + ')} | ${tierLabel} plan`);
    lines.push(`**Processing:** ${selectedCount} highest-severity findings`);
    if (deferredCount > 0) {
      lines.push(`**Deferred:** ${deferredCount} (will be picked up on next scan with available budget)`);
    }

    lines.push('');
    lines.push('| # | Severity | CWE | File | Status |');
    lines.push('|---|----------|-----|------|--------|');

    // Selected findings
    for (let i = 0; i < scanPlan.selected.length; i++) {
      const f = scanPlan.selected[i];
      lines.push(`| ${i + 1} | ${capitalize(f.severity)} | ${f.cwe_id} | \`${f.file_path}:${f.line}\` | ✅ Processing |`);
    }

    // Deferred findings
    for (let i = 0; i < scanPlan.deferred.length; i++) {
      const f = scanPlan.deferred[i];
      const num = scanPlan.selected.length + i + 1;
      lines.push(`| ${num} | ${capitalize(f.severity)} | ${f.cwe_id} | \`${f.file_path}:${f.line}\` | ⏳ Deferred |`);
    }
  } else if (createdIssues.length === 0) {
    // No plan, no issues created
    lines.push(`Found **${vulnerabilityCount}** potential vulnerabilities.`);
    lines.push('**Budget:** information unavailable — using conservative default');
  } else {
    // Fallback — no plan but issues were created
    lines.push(`Found **${vulnerabilityCount}** potential vulnerabilities. Created **${createdIssues.length}** issues for validation.`);
    lines.push('**Budget:** information unavailable — using conservative default');
    lines.push('');
    lines.push('| Issue | Type |');
    lines.push('|-------|------|');

    for (const issue of createdIssues) {
      const cwe = issue.cwe_id || issue.vulnerabilityType || 'Unknown';
      lines.push(`| [#${issue.number}](../../issues/${issue.number}) | ${cwe} |`);
    }
  }

  lines.push('');
  lines.push('---');
  lines.push('*Generated by [RSOLV](https://rsolv.dev) — AI-powered security vulnerability remediation*');

  try {
    appendFileSync(summaryFile, lines.join('\n') + '\n');
    logger.info('[JobSummary] Scan summary written');
  } catch (error) {
    logger.warn('[JobSummary] Failed to write scan summary', error);
  }
}

function capitalize(s: string): string {
  return s.charAt(0).toUpperCase() + s.slice(1);
}

interface IssueResult {
  issueNumber: number;
  classification: string;
  prUrl?: string;
}

/**
 * Write a job summary for a PROCESS (validate+mitigate) phase result.
 *
 * When issueResults are available (per-issue classification data from the
 * process loop), renders a table with per-issue outcomes. Otherwise falls
 * back to a generic message.
 */
export function writeProcessSummary(
  repoFullName: string,
  issueNumber: number,
  result: ProcessResult
): void {
  const summaryFile = process.env.GITHUB_STEP_SUMMARY;
  if (!summaryFile) return;

  const data = (result.data || {}) as Record<string, unknown>;
  const issueResults = data.issueResults as IssueResult[] | undefined;

  const lines: string[] = [
    `## 🔒 RSOLV Results — ${repoFullName}`,
    '',
  ];

  if (!result.success && !issueResults?.length) {
    lines.push(`❌ Processing failed: ${result.error || 'Unknown error'}`);
  } else if (issueResults && issueResults.length > 0) {
    // Per-issue table
    lines.push('| Issue | Result | Action |');
    lines.push('|-------|--------|--------|');

    for (const ir of issueResults) {
      const { emoji, label } = classificationDisplay(ir.classification);
      const action = ir.prUrl
        ? `[Fix PR](${ir.prUrl})`
        : ir.classification.startsWith('false_positive') ? 'No action needed' : '—';
      lines.push(`| [#${ir.issueNumber}](../../issues/${ir.issueNumber}) | ${emoji} ${label} | ${action} |`);
    }
  } else {
    // Fallback for single-issue mode or missing data
    const classification = extractClassification(data);
    const prUrl = extractPrUrl(data);
    const { emoji, label } = classificationDisplay(classification || 'unknown');

    lines.push(`**Issue #${issueNumber}:** ${emoji} ${label}`);
    if (prUrl) {
      lines.push('');
      lines.push(`🔧 **Fix PR:** [${prUrl}](${prUrl})`);
    }
  }

  lines.push('');
  lines.push('---');
  lines.push('*Generated by [RSOLV](https://rsolv.dev) — AI-powered security vulnerability remediation*');

  try {
    appendFileSync(summaryFile, lines.join('\n') + '\n');
    logger.info(`[JobSummary] Process summary written for #${issueNumber}`);
  } catch (error) {
    logger.warn('[JobSummary] Failed to write process summary', error);
  }
}

function classificationDisplay(classification: string): { emoji: string; label: string } {
  switch (classification) {
  case 'validated':
    return { emoji: '✅', label: 'Vulnerability confirmed' };
  case 'false_positive_defense_confirmed':
    return { emoji: '🛡️', label: 'Defense confirmed — not exploitable' };
  case 'false_positive_counter_indicated':
    return { emoji: '🛡️', label: 'False positive — not exploitable' };
  case 'false_positive':
    return { emoji: '⚪', label: 'Not validated' };
  case 'infrastructure_failure':
    return { emoji: '⚠️', label: 'Infrastructure issue' };
  case 'max_turns_exceeded':
    return { emoji: '⏱️', label: 'Timed out' };
  default:
    return { emoji: '❓', label: classification };
  }
}

function extractClassification(data: Record<string, unknown>): string | undefined {
  // Classification may be nested under validate or at top level
  if (data.classification) return String(data.classification);
  const validate = data.validate as Record<string, unknown> | undefined;
  if (validate?.classification) return String(validate.classification);
  return undefined;
}

function extractPrUrl(data: Record<string, unknown>): string | undefined {
  if (data.pr_url) return String(data.pr_url);
  const mitigate = data.mitigate as Record<string, unknown> | undefined;
  if (mitigate?.pr_url) return String(mitigate.pr_url);
  return undefined;
}
