name: Manual Trigger for Testing

on:
  workflow_dispatch:
    inputs:
      issue_number:
        description: 'Issue number to process'
        required: true
      repository:
        description: 'Repository name (e.g., owner/repo)'
        required: true
        default: 'RSOLV-dev/RSOLV-action'

jobs:
  rsolv-fix:
    runs-on: ubuntu-latest
    name: Generate fix for issue
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Run RSOLV Action
        uses: ./ # Uses the action in the root directory
        with:
          api_key: ${{ secrets.RSOLV_API_KEY }}
          # Pass the manually provided issue number to the action
          issue_number: ${{ github.event.inputs.issue_number }}
          target_repository: ${{ github.event.inputs.repository }}