name: RSOLV Dogfood

on:
  issues:
    types: [opened, labeled]
  schedule:
    # Run daily at 2 AM UTC
    - cron: '0 2 * * *'
  workflow_dispatch:
    inputs:
      issue_number:
        description: 'Specific issue number to process (optional)'
        required: false
        type: string

jobs:
  rsolv-automation:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      contents: write
      pull-requests: write
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Run RSOLV Action
        uses: ./  # Use the action from the current repository
        with:
          api_key: ${{ secrets.RSOLV_API_KEY }}
          issue_label: 'rsolv:automate'
          config_path: '.github/rsolv.yml'
          # For dogfooding, we might want to use a development API URL
          # api_url: 'https://dev-api.rsolv.ai'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # Optional: Add AI provider tokens if not using RSOLV API
          # ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
          # OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}