name: Security Scan Demo

on:
  workflow_dispatch:
    inputs:
      create_issues:
        description: 'Create GitHub issues for vulnerabilities'
        required: false
        default: 'true'
        type: choice
        options:
          - 'true'
          - 'false'

jobs:
  scan-repository:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Run RSOLV Security Scan
        id: scan
        uses: ./
        with:
          api_key: ${{ secrets.RSOLV_API_KEY }}
          scan_mode: scan
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Display scan results
        if: always()
        run: |
          echo "=== Security Scan Complete ==="
          echo "Scan results available in GitHub Actions output"
          
      - name: Upload scan results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: security-scan-results
          path: |
            scan-results.json
          if-no-files-found: ignore