name: Verify Pattern Count
on:
  push:
    paths:
      - 'src/security/minimal-patterns.ts'
      - 'README.md'
      - 'docs/**'
  pull_request:
    paths:
      - 'src/security/minimal-patterns.ts'
      - 'README.md'
      - 'docs/**'

jobs:
  verify-counts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
          
      - name: Count Patterns
        run: |
          # This workflow verifies the minimal-patterns.ts test pattern count.
          # The actual pattern count (~170) is served via the RSOLV-platform API.
          # These 26 patterns are for testing/CI purposes only.

          # Count test patterns in minimal-patterns.ts
          TOTAL=$(grep -o "^\s*id:" src/security/minimal-patterns.ts | wc -l)
          echo "TOTAL_PATTERNS=$TOTAL" >> $GITHUB_ENV
          echo "Found $TOTAL test patterns in minimal-patterns.ts"
          echo "Note: Production pattern count (~170) is served via API"
          
      - name: Verify README Claims
        run: |
          # Check if README contains the API pattern count (170+)
          # Note: This is separate from the 26 test patterns verified above
          README_COUNT=$(grep -oP "\d+(?=\+ Security Patterns)" README.md | head -1)
          if [ -z "$README_COUNT" ]; then
            echo "❌ Could not find pattern count in README.md"
            exit 1
          fi
          if [ "$README_COUNT" -lt 170 ]; then
            echo "❌ README claims $README_COUNT+ patterns but should claim 170+ (API patterns)"
            exit 1
          fi
          echo "✅ README correctly claims $README_COUNT+ patterns (API count)"
          echo "✅ Test patterns in minimal-patterns.ts: $TOTAL_PATTERNS"
          
      - name: Update Pattern Inventory
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          # Create a pattern inventory file
          cat > PATTERN_INVENTORY_VERIFIED.md << EOF
          # Verified Pattern Inventory

          Last Updated: $(date -u +"%Y-%m-%d %H:%M:%S UTC")

          ## Pattern Counts

          - **Production Patterns**: ~170 patterns (served via RSOLV-platform API)
          - **Test Patterns**: $TOTAL_PATTERNS patterns (in src/security/minimal-patterns.ts)

          ## About the Counts

          The 26 patterns in minimal-patterns.ts are for testing and CI purposes only.
          Production deployments require the full ~170 pattern set from the RSOLV-platform API for comprehensive
          vulnerability detection across 8 languages. If the backend is unavailable, customers must wait for it
          to come back online.

          ## Verification

          This count is automatically verified by CI/CD on every commit.
          EOF
          
      - name: Fail if Inflated
        run: |
          # Fail if we detect old inflated counts (448 or 80)
          if grep -qE "(448|80)\+" README.md 2>/dev/null; then
            echo "❌ Found inflated pattern count (448+ or 80+) in README.md"
            echo "Should be 170+ (API patterns)"
            exit 1
          fi

          # Also check docs directory if it exists (excluding archived docs)
          if [ -d "docs" ]; then
            if grep -rqE "(448|80)\+" docs/ --exclude-dir=archived 2>/dev/null; then
              echo "❌ Found inflated pattern count (448+ or 80+) in docs/"
              echo "Should be 170+ (API patterns)"
              exit 1
            fi
          fi

          echo "✅ No inflated pattern counts found"